type: "transformation"
version: "1.0"
pipeline:
  components:
    mtln_qs_sf_account:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_account"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_account"
        timeOffset:
        columnNames:
        - "Id"
        - "Name"
        - "OwnerId"
        - "BillingCountry"
        - "BillingState"
    mtln_qs_sf_user:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_user"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_user"
        timeOffset:
        columnNames:
        - "Id"
        - "Name"
    mtln_qs_sf_opportunity:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_opportunity"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_opportunity"
        timeOffset:
        columnNames:
        - "Id"
        - "AccountId"
        - "Name"
    Join:
      type: "join"
      sources:
      - "mtln_qs_sf_account"
      - "mtln_qs_sf_opportunity"
      - "mtln_qs_sf_user"
      parameters:
        componentName: "Join"
        mainTable: "mtln_qs_sf_account"
        mainTableAlias: "ccna1"
        joins:
        - - "mtln_qs_sf_user"
          - "sra2"
          - "Left"
        - - "mtln_qs_sf_opportunity"
          - "ppra3"
          - "Inner"
        joinExpressions:
        - - "\"ccna1\".\"OwnerId\" = \"sra2\".\"Id\""
          - "ccna1_Left_sra2"
        - - "\"ccna1\".\"Id\" = \"ppra3\".\"AccountId\""
          - "ccna1_Inner_ppra3"
        columnMappings:
        - - "ccna1.Id"
          - "ccna1_Id"
        - - "ccna1.Name"
          - "ccna1_Name"
        - - "ccna1.OwnerId"
          - "ccna1_OwnerId"
        - - "ccna1.BillingCountry"
          - "ccna1_BillingCountry"
        - - "ccna1.BillingState"
          - "ccna1_BillingState"
        - - "sra2.Id"
          - "sra2_Id"
        - - "sra2.Name"
          - "sra2_Name"
        - - "ppra3.Id"
          - "ppra3_Id"
        - - "ppra3.AccountId"
          - "ppra3_AccountId"
        - - "ppra3.Name"
          - "ppra3_Name"
    Filter:
      type: "filter"
      sources:
      - "Join"
      parameters:
        componentName: "Filter"
        filterConditions:
        - - "ccna1_Id"
          - "Not"
          - "Null or blank"
          - ""
        combineCondition: "And"
    Rewrite mtln_qs_sf_opportunities_with_account:
      type: "rewrite-table"
      sources:
      - "Filter"
      parameters:
        componentName: "Rewrite mtln_qs_sf_opportunities_with_account"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_opportunities_with_account"
        warehouse: "[Environment Default]"
        orderBy:
design:
  components:
    mtln_qs_sf_account:
      position:
        x: 0
        y: -100
      tempMetlId: 4
    mtln_qs_sf_user:
      position:
        x: 0
        y: 0
      tempMetlId: 5
    mtln_qs_sf_opportunity:
      position:
        x: 0
        y: 100
      tempMetlId: 6
    Join:
      position:
        x: 150
        y: 0
      tempMetlId: 1
    Filter:
      position:
        x: 300
        y: 0
      tempMetlId: 2
    Rewrite mtln_qs_sf_opportunities_with_account:
      position:
        x: 450
        y: 0
      tempMetlId: 3
  notes:
    1:
      position:
        x: 200
        y: -130
      size:
        height: 200
        width: 240
      theme: "white"
      content: "Add your own filters here if you want to apply them before the integra\
        ted report is generated"
    2:
      position:
        x: -370
        y: -100
      size:
        height: 100
        width: 300
      theme: "white"
      content: "Add your own Table Inputs here to customize the integration with your \
        own data"
