type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Create sequence"
      parameters:
        componentName: "Start"
    Salesforce Account (incremental bronze):
      type: "salesforce-query"
      transitions:
        success:
        - "Bronze-to-Silver"
      parameters:
        componentName: "Salesforce Account (incremental bronze)"
        basicAdvancedMode: "Basic"
        authenticationMethod: "OAuth"
        useSandbox: "No"
        authentication: "${SalesforceOAuthName}"
        connectionOptions:
        dataSource: "Account"
        dataSelection:
        - "Id"
        - "Name"
        - "AnnualRevenue"
        - "LastModifiedDate"
        dataSourceFilter:
        - - "LastModifiedDate"
          - "Is"
          - "Greater than"
          - "${HighWaterMark}"
        combineFilters: "And"
        limit: ""
        type: "Standard"
        primaryKeys:
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_account"
        stage: "[Custom]"
        stagePlatform: "Snowflake Managed"
        loadOptions:
        autoDebug: "Off"
    Bronze-to-Silver:
      type: "run-transformation"
      transitions:
        success:
        - "Silver-to-Gold"
      parameters:
        componentName: "Bronze-to-Silver"
        transformationJob: "Data Engineering/Incremental Load Strategy Medallion Schema/qs-incremental-load-salesforce-trans-to-silver"
        setScalarVariables:
        setGridVariables:
    Silver-to-Gold:
      type: "run-transformation"
      parameters:
        componentName: "Silver-to-Gold"
        transformationJob: "Data Engineering/Incremental Load Strategy Medallion Schema/qs-incremental-load-salesforce-trans-to-gold"
        setScalarVariables:
        setGridVariables:
    Create Silver ODS Table:
      type: "create-table"
      transitions:
        success:
        - "Set HighWaterMark"
      parameters:
        componentName: "Create Silver ODS Table"
        createReplace: "Create if not exists"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        newTableName: "mtln_qs_sf_ods_account"
        tableType: "Permanent"
        columns:
        - - "surrogate_key"
          - "NUMBER"
          - "12"
          - "0"
          - "\"mtln_qs_sf_ods_account_seq\".NEXTVAL"
          - "Yes"
          - "Yes"
          - ""
        - - "id"
          - "VARCHAR"
          - "32"
          - ""
          - ""
          - "Yes"
          - "No"
          - ""
        - - "account_name"
          - "VARCHAR"
          - "1024"
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "annual_revenue"
          - "NUMBER"
          - "20"
          - "0"
          - ""
          - "No"
          - "No"
          - ""
        - - "last_modified_timestamp"
          - "TIMESTAMP_NTZ"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        defaultDdlCollation:
        primaryKeys:
        clusteringKeys:
        dataRetentionTimeInDays:
        comment:
    Create sequence:
      type: "sql-script"
      transitions:
        success:
        - "Create Silver ODS Table"
      parameters:
        componentName: "Create sequence"
        sqlScript: "CREATE SEQUENCE IF NOT EXISTS \"mtln_qs_sf_ods_account_seq\""
    Set HighWaterMark:
      type: "query-to-scalar"
      transitions:
        success:
        - "Print HighWaterMark"
        - "Salesforce Account (incremental bronze)"
      parameters:
        componentName: "Set HighWaterMark"
        mode: "Advanced"
        query: "SELECT COALESCE(TO_CHAR(MAX(\"last_modified_timestamp\"), 'YYYY-MM-DD\
          \ HH24:MI:SS'), '1990-01-01 00:00:00') AS HWM\r\nFROM \"mtln_qs_sf_ods_account\""
        scalarVariableMapping:
        - - "HighWaterMark"
          - "HWM"
    Print HighWaterMark:
      type: "print-variables"
      parameters:
        componentName: "Print HighWaterMark"
        variablesToPrint:
        - - "HighWaterMark"
        prefixText:
        includeVariableName: "No"
  variables:
    SalesforceOAuthName:
      metadata:
        type: "TEXT"
        description: "Name of your Salesforce OAuth"
        scope: "COPIED"
        visibility: "PRIVATE"
      defaultValue: "Your-Salesforce-OAuth-name"
    HighWaterMark:
      metadata:
        type: "TEXT"
        description: "The maximum last_modified_timestamp from the ODS table, as YYYY-MM-DD\
          \ HH24:MI:SS"
        scope: "COPIED"
        visibility: "PRIVATE"
      defaultValue: "1990-01-01 00:00:00"
design:
  components:
    Start:
      position:
        x: -180
        "y": 0
      tempMetlId: 1
    Salesforce Account (incremental bronze):
      position:
        x: 430
        "y": 0
      tempMetlId: 2
    Bronze-to-Silver:
      position:
        x: 600
        "y": 0
      tempMetlId: 3
    Silver-to-Gold:
      position:
        x: 740
        "y": 0
      tempMetlId: 4
    Create Silver ODS Table:
      position:
        x: 70
        "y": 0
      tempMetlId: 5
    Create sequence:
      position:
        x: -60
        "y": 0
      tempMetlId: 6
    Set HighWaterMark:
      position:
        x: 260
        "y": 0
      tempMetlId: 7
    Print HighWaterMark:
      position:
        x: 330
        "y": 110
      tempMetlId: 8
  notes:
    "1":
      position:
        x: 330
        "y": -130
      size:
        height: 98
        width: 320
      theme: "light-red"
      content: "Please set the default value of the `SalesforceOAuthName` pipeline\
        \ variable before validating or running"
    "2":
      position:
        x: -110
        "y": -130
      size:
        height: 98
        width: 340
      theme: "light-green"
      content: "Incremental load strategy medallion schema example for Snowflake"
