type: "transformation"
version: "1.0"
pipeline:
  components:
    Rewrite Table 0:
      type: "rewrite-table"
      sources:
      - "Rename 0"
      parameters:
        componentName: "Rewrite Table 0"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "flights_aggregate_count"
    Calculator 0:
      type: "calculator"
      sources:
      - "Aggregate 0"
      parameters:
        componentName: "Calculator 0"
        includeInputColumns: "Yes"
        calculations:
        - - "\"Origin\" || '-->' || \"Dest\""
          - "flight_leg"
    Rename 0:
      type: "rename"
      sources:
      - "Calculator 0"
      parameters:
        componentName: "Rename 0"
        columnMapping:
        - - "flight_leg"
          - "flight_leg"
        - - "count_Year"
          - "flight_count"
    raw_flights:
      type: "table-input"
      parameters:
        componentName: "raw_flights"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "raw_flights"
        columnNames:
        - "Year"
        - "Month"
        - "DayofMonth"
        - "DayOfWeek"
        - "DepTime"
        - "CRSDepTime"
        - "ArrTime"
        - "CRSArrTime"
        - "UniqueCarrier"
        - "FlightNum"
        - "TailNum"
        - "ActualElapsedTime"
        - "CRSElapsedTime"
        - "AirTime"
        - "ArrDelay"
        - "DepDelay"
        - "Origin"
        - "Dest"
        - "Distance"
        - "TaxiIn"
        - "TaxiOut"
        - "Cancelled"
        - "CancellationCode"
        - "Diverted"
        - "CarrierDelay"
        - "WeatherDelay"
        - "NASDelay"
        - "SecurityDelay"
        - "LateAircraftDelay"
        timeOffset: ""
    Aggregate 0:
      type: "aggregate"
      sources:
      - "raw_flights"
      parameters:
        componentName: "Aggregate 0"
        groupings:
        - "Origin"
        - "Dest"
        aggregations:
        - - "Year"
          - "Count"
        groupingType: "Group By"
design:
  components:
    Rewrite Table 0:
      position:
        x: 803
        "y": 139
      tempMetlId: 71218
    Calculator 0:
      position:
        x: 523
        "y": 141
      tempMetlId: 71220
    Rename 0:
      position:
        x: 664
        "y": 138
      tempMetlId: 71221
    raw_flights:
      position:
        x: 279
        "y": 143
      tempMetlId: 71222
    Aggregate 0:
      position:
        x: 392
        "y": 148
      tempMetlId: 71223
