type: "transformation"
version: "1.0"
pipeline:
  components:
    cfb_upset:
      type: "table-output"
      sources:
      - "Join & Include Teams' QB"
      parameters:
        componentName: "cfb_upset"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "cfb_upset"
        fixDataTypeMismatches: "No"
        columnMapping:
        - - "actualWinner"
          - "actualWinner"
        - - "projectedWinner"
          - "projectedWinner"
        - - "pointDifferential"
          - "pointDifferential"
        - - "result"
          - "result"
        - - "awayTeam"
          - "awayTeam"
        - - "awayScore"
          - "awayScore"
        - - "awayTeamQB"
          - "awayTeamQB"
        - - "homeTeam"
          - "homeTeam"
        - - "homeScore"
          - "homeScore"
        - - "homeTeamQB"
          - "homeTeamQB"
        - - "formattedSpread"
          - "formattedSpread"
        orderBy:
        outputMode: "Append"
    Example & Delete:
      type: "extract-nested-data-sf"
      sources:
      - "cfb_odds"
      parameters:
        componentName: "Example & Delete"
        includeInputColumns: "No"
        columns:
        - name: "awayConference"
          datatype: "VARIANT"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "awayConference"
          isArray: "false"
          include: "true"
        - name: "awayScore"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "awayScore"
          isArray: "false"
          include: "true"
        - name: "awayTeam"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "awayTeam"
          isArray: "false"
          include: "true"
        - name: "homeConference"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "homeConference"
          isArray: "false"
          include: "true"
        - name: "homeScore"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "homeScore"
          isArray: "false"
          include: "true"
        - name: "homeTeam"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "homeTeam"
          isArray: "false"
          include: "true"
        - name: "lines"
          datatype: "VARIANT"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "lines"
          isArray: "false"
          include: "true"
        - name: "season"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "season"
          isArray: "false"
          include: "true"
        - name: "seasonType"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "seasonType"
          isArray: "false"
          include: "true"
        - name: "week"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "week"
          isArray: "false"
          include: "true"
        - name: "id"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "id"
          isArray: "false"
          include: "true"
        outerJoin: "False"
        inputAlias: "i"
        arrayPrefix: "f"
    Join & Include Teams' QB:
      type: "join"
      sources:
      - "cfb_stats_flat"
      - "Upset Amount"
      parameters:
        componentName: "Join & Include Teams' QB"
        mainTable: "Upset Amount"
        mainTableAlias: "games"
        joins:
        - - "cfb_stats_flat"
          - "away_stats"
          - "Left"
        - - "cfb_stats_flat"
          - "home_stats"
          - "Left"
        joinExpressions:
        - - "\"games\".\"awayTeam\" = \"away_stats\".\"team\"\nAND \"away_stats\"\
            .\"statType\" = 'YDS' \nAND \"away_stats\".\"category\" = 'passing'\n\
            AND \"away_stats\".\"stat\" = (select max(\"stat\") from \"DEV_DB\".\"\
            KAREY\".\"cfb_stats_flat\" AS \"s\" where \n\t\t\t\t\t\"s\".\"team\" =\
            \ \"away_stats\".\"team\" AND \"s\".\"statType\" = 'YDS' AND \"s\".\"\
            category\" = 'passing')"
          - "games_Left_away_stats"
        - - "\"games\".\"homeTeam\" = \"home_stats\".\"team\"\nAND \"home_stats\"\
            .\"statType\" = 'YDS' \nAND \"home_stats\".\"category\" = 'passing'\n\
            AND \"home_stats\".\"stat\" = (select max(\"stat\") from \"DEV_DB\".\"\
            KAREY\".\"cfb_stats_flat\" AS \"s\" where \n\t\t\t\t\t\"s\".\"team\" =\
            \ \"home_stats\".\"team\" AND \"s\".\"statType\" = 'YDS' AND \"s\".\"\
            category\" = 'passing')"
          - "games_Left_home_stats"
        columnMappings:
        - - "games.actualWinner"
          - "actualWinner"
        - - "games.projectedWinner"
          - "projectedWinner"
        - - "games.pointDifferential"
          - "pointDifferential"
        - - "games.season"
          - "season"
        - - "games.result"
          - "result"
        - - "games.awayTeam"
          - "awayTeam"
        - - "games.awayScore"
          - "awayScore"
        - - "away_stats.player"
          - "awayTeamQB"
        - - "games.homeTeam"
          - "homeTeam"
        - - "games.homeScore"
          - "homeScore"
        - - "home_stats.player"
          - "homeTeamQB"
        - - "games.formattedSpread"
          - "formattedSpread"
    cfb_odds:
      type: "table-input"
      parameters:
        componentName: "cfb_odds"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "cfb_odds"
        columnNames:
        - "Data Value"
        timeOffset: ""
    cfb_stats_flat:
      type: "table-input"
      parameters:
        componentName: "cfb_stats_flat"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "cfb_stats_flat"
        columnNames:
        - "category"
        - "stat"
        - "statType"
        - "team"
        - "player"
        timeOffset: ""
    Upset Amount:
      type: "calculator"
      sources:
      - "Projected & Actual Winner"
      parameters:
        componentName: "Upset Amount"
        includeInputColumns: "Yes"
        calculations:
        - - "CASE WHEN trim(\"projectedWinner\",' ') <> trim(\"actualWinner\",' ')\
            \ THEN (\"spread\"+\"scoreDifference\") \nWHEN trim(\"projectedWinner\"\
            ,' ') = trim(\"actualWinner\",' ') THEN ABS(\"scoreDifference\"-\"spread\"\
            ) \nELSE 0 END "
          - "pointDifferential"
        - - "CASE WHEN trim(\"projectedWinner\",' ') <> trim(\"actualWinner\",' ')\
            \ THEN 'upset' \nELSE 'expected winner won' END"
          - "result"
    Flatten Multi Variant Layers:
      type: "sql"
      sources:
      - "cfb_odds"
      parameters:
        componentName: "Flatten Multi Variant Layers"
        query: "SELECT \n\"i\".\"Data Value\":\"awayScore\"::NUMBER AS \"awayScore\"\
          ,\n\"i\".\"Data Value\":\"awayTeam\"::VARCHAR AS \"awayTeam\",\n\"i\".\"\
          Data Value\":\"homeScore\"::NUMBER AS \"homeScore\",\n\"i\".\"Data Value\"\
          :\"homeTeam\"::VARCHAR AS \"homeTeam\",\n\"i\".\"Data Value\":\"season\"\
          ::NUMBER AS \"season\",\n\"n\".value:\"formattedSpread\"::VARCHAR as \"\
          formattedSpread\",\n\"n\".value:\"overUnder\"::VARCHAR as \"overUnder\"\
          ,\n\"n\".value:\"provider\"::VARCHAR as \"provider\",\n\"n\".value:\"spread\"\
          ::VARCHAR as \"spread\"\n\nFROM \n\"DEV_DB\".\"KAREY\".\"cfb_odds\" \"i\"\
          ,\nlateral flatten( input => \"i\".\"Data Value\":\"lines\") \"n\""
    Filter "First" Duplicate:
      type: "filter"
      sources:
      - "Set Duplicate Row Count"
      parameters:
        componentName: "Filter \"First\" Duplicate"
        filterConditions:
        - - "rn"
          - "Is"
          - "Equal to"
          - "1"
        combineCondition: "AND"
    Projected & Actual Winner:
      type: "calculator"
      sources:
      - "Filter \"First\" Duplicate"
      parameters:
        componentName: "Projected & Actual Winner"
        includeInputColumns: "Yes"
        calculations:
        - - "regexp_replace(\"formattedSpread\",'-.*','')"
          - "projectedWinner"
        - - "IFNULL(LTRIM(\"spread\",'- '),0)"
          - "spread"
        - - "CASE WHEN \"homeScore\" < \"awayScore\" THEN \"awayTeam\" ELSE \"homeTeam\"\
            \ END"
          - "actualWinner"
        - - "ABS(\"awayScore\"-\"homeScore\")"
          - "scoreDifference"
    Set Duplicate Row Count:
      type: "rank"
      sources:
      - "Flatten Multi Variant Layers"
      parameters:
        componentName: "Set Duplicate Row Count"
        includeInputColumns: "Yes"
        partitionData:
        - "awayTeam"
        - "homeTeam"
        - "season"
        orderingWithinPartitions:
        - - "awayTeam"
          - "Asc"
        - - "homeTeam"
          - "Asc"
        - - "season"
          - "Asc"
        functions:
        - - "Row Number"
          - "rn"
design:
  components:
    cfb_upset:
      position:
        x: 1008
        "y": 80
      tempMetlId: 71472
    Example & Delete:
      position:
        x: 336
        "y": 176
      tempMetlId: 71474
    Join & Include Teams' QB:
      position:
        x: 832
        "y": 80
      tempMetlId: 71475
    cfb_odds:
      position:
        x: 160
        "y": 80
      tempMetlId: 71476
    cfb_stats_flat:
      position:
        x: 832
        "y": 0
      tempMetlId: 71477
    Upset Amount:
      position:
        x: 656
        "y": 80
      tempMetlId: 71478
    Flatten Multi Variant Layers:
      position:
        x: 336
        "y": 80
      tempMetlId: 71479
    Filter "First" Duplicate:
      position:
        x: 480
        "y": 80
      tempMetlId: 71480
    Projected & Actual Winner:
      position:
        x: 656
        "y": 0
      tempMetlId: 71481
    Set Duplicate Row Count:
      position:
        x: 480
        "y": 0
      tempMetlId: 71483
  notes:
    "71473":
      position:
        x: 128
        "y": -58
      size:
        height: 100
        width: 257
      theme: "green"
      content: |
        **ALMOST AT THE FINISH LINE**

        - Flatten Odds to Structured format
        - Determine size of upset, based on projected vs actual results
        - Enrich w quarterback data
        - Write to table in Snowflake
