type: "transformation"
version: "1.0"
pipeline:
  components:
    Extract Nested Data 0:
      type: "extract-nested-data-sf"
      sources:
      - "cfb_player_stats_2023"
      parameters:
        componentName: "Extract Nested Data 0"
        includeInputColumns: "No"
        columns:
        - name: "awayConference"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "awayConference"
          isArray: "false"
          include: "true"
        - name: "awayScore"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "awayScore"
          isArray: "false"
          include: "true"
        - name: "awayTeam"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "awayTeam"
          isArray: "false"
          include: "true"
        - name: "homeConference"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "homeConference"
          isArray: "false"
          include: "true"
        - name: "homeScore"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "homeScore"
          isArray: "false"
          include: "true"
        - name: "homeTeam"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "homeTeam"
          isArray: "false"
          include: "true"
        - name: "lines"
          datatype: "VARIANT"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "lines"
          isArray: "true"
          include: "false"
          childElements:
          - name: "lines-element"
            datatype: "VARIANT"
            size: "0"
            decimalPlaces: "0"
            columnName: "Data Value"
            aliasName: "lines-element"
            isArray: "false"
            include: "false"
            childElements:
            - name: "awayMoneyline"
              datatype: "VARIANT"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "awayMoneyline"
              isArray: "false"
              include: "true"
            - name: "homeMoneyline"
              datatype: "VARIANT"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "homeMoneyline"
              isArray: "false"
              include: "true"
            - name: "overUnder"
              datatype: "VARIANT"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "overUnder"
              isArray: "false"
              include: "true"
            - name: "overUnderOpen"
              datatype: "VARIANT"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "overUnderOpen"
              isArray: "false"
              include: "true"
            - name: "spread"
              datatype: "VARCHAR"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "spread"
              isArray: "false"
              include: "true"
            - name: "spreadOpen"
              datatype: "VARIANT"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "spreadOpen"
              isArray: "false"
              include: "true"
            - name: "provider"
              datatype: "VARCHAR"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "provider"
              isArray: "false"
              include: "true"
            - name: "formattedSpread"
              datatype: "VARCHAR"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "formattedSpread"
              isArray: "false"
              include: "true"
        - name: "seasonType"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "seasonType"
          isArray: "false"
          include: "true"
        - name: "week"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "week"
          isArray: "false"
          include: "true"
        - name: "season"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "season"
          isArray: "false"
          include: "true"
        - name: "startDate"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "startDate"
          isArray: "false"
          include: "true"
        - name: "id"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "id"
          isArray: "false"
          include: "true"
        outerJoin: "False"
        inputAlias: "i"
        arrayPrefix: "f"
        castingMethod: "Fail on invalid data"
        caseColumnAliasNames: "No"
    cfb_player_stats_2023:
      type: "table-input"
      parameters:
        componentName: "cfb_player_stats_2023"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "cfb_odds_2023"
        columnNames:
        - "Data Value"
        timeOffset: ""
    Rewrite Table 0:
      type: "rewrite-table"
      sources:
      - "Extract Nested Data 0"
      parameters:
        componentName: "Rewrite Table 0"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "cfb_odds_2023_structured"
        orderBy:
design:
  components:
    Extract Nested Data 0:
      position:
        x: 352
        "y": 128
      tempMetlId: 1635239
    cfb_player_stats_2023:
      position:
        x: 181
        "y": 135
      tempMetlId: 1635250
    Rewrite Table 0:
      position:
        x: 528
        "y": 128
      tempMetlId: 1635282
