type: "transformation"
version: "1.0"
pipeline:
  components:
    Aggregate 1990:
      type: "aggregate"
      sources:
      - "Filter 1990"
      parameters:
        componentName: "Aggregate 1990"
        groupings:
        - "origin"
        - "dest"
        aggregations:
        - - "year"
          - "Count"
        - - "actualeslapsedtime"
          - "Average"
        groupingType: "Group By"
    Filter 1980:
      type: "filter"
      sources:
      - "Add Decade Column"
      parameters:
        componentName: "Filter 1980"
        filterConditions:
        - - "decade"
          - "Is"
          - "Equal to"
          - "1980"
        - - "actualeslapsedtime"
          - "Not"
          - "Null"
          - ""
        combineCondition: "AND"
    Calculator 1990:
      type: "calculator"
      sources:
      - "Aggregate 1990"
      parameters:
        componentName: "Calculator 1990"
        includeInputColumns: "Yes"
        calculations:
        - - "\"origin\" || '-->' || \"dest\""
          - "flight_leg"
    Read raw_flights:
      type: "table-input"
      parameters:
        componentName: "Read raw_flights"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "raw_flights"
        columnNames:
        - "year"
        - "month"
        - "dayofmonth"
        - "dayofweek"
        - "deptime"
        - "crsdeptime"
        - "arrtime"
        - "crsarrtime"
        - "uniquecarrier"
        - "flightnum"
        - "tailnum"
        - "actualeslapsedtime"
        - "crselapsedtime"
        - "airtime"
        - "arrdelay"
        - "depdelay"
        - "origin"
        - "dest"
        - "distance"
        - "taxiin"
        - "taxiout"
        - "cancelled"
        - "cancellationcode"
        - "diverted"
        - "carrierdelay"
        - "weatherdelay"
        - "nasdelay"
        - "securitydelay"
        - "lateaircraftdelay"
        timeOffset: ""
    Add Decade Column:
      type: "calculator"
      sources:
      - "Read raw_flights"
      parameters:
        componentName: "Add Decade Column"
        includeInputColumns: "Yes"
        calculations:
        - - "IFF(\"year\" between 1980 and 1989,1980,IFF(\"year\" between 1990 and\
            \ 1999,1990,null))"
          - "decade"
    airports:
      type: "table-input"
      parameters:
        componentName: "airports"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "airports"
        columnNames:
        - "airport_data"
        timeOffset: ""
    Flatten airports:
      type: "flatten-variant"
      sources:
      - "airports"
      parameters:
        componentName: "Flatten airports"
        includeInputColumns: "No"
        columnMapping:
        - - "airport_data"
          - "airport"
          - "VARCHAR"
          - ""
        - - "airport_data"
          - "iata"
          - "VARCHAR"
          - ""
        - - "airport_data"
          - "city"
          - "VARCHAR"
          - ""
        - - "airport_data"
          - "state"
          - "VARCHAR"
          - ""
        - - "airport_data"
          - "country"
          - "VARCHAR"
          - ""
        - - "airport_data"
          - "lat"
          - "FLOAT"
          - ""
        - - "airport_data"
          - "long"
          - "FLOAT"
          - ""
        columnFlattens:
    Table Output 0:
      type: "table-output"
      sources:
      - "Calculator 0"
      parameters:
        componentName: "Table Output 0"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: ""
        fixDataTypeMismatches: "No"
        columnMapping:
        outputMode: "Append"
    Calculator 0:
      type: "calculator"
      sources:
      - "Join 1"
      parameters:
        componentName: "Calculator 0"
        includeInputColumns: "Yes"
        calculations:
    Filter 1990:
      type: "filter"
      sources:
      - "Add Decade Column"
      parameters:
        componentName: "Filter 1990"
        filterConditions:
        - - "decade"
          - "Is"
          - "Equal to"
          - "1990"
        - - "actualeslapsedtime"
          - "Not"
          - "Null"
          - ""
        combineCondition: "AND"
    Join 1:
      type: "join"
      sources:
      - "Joined Flights"
      - "Flatten airports"
      parameters:
        componentName: "Join 1"
        mainTable: "Joined Flights"
        mainTableAlias: "flights"
        joins:
        - - "Flatten airports"
          - "origin"
          - "Left"
        - - "Flatten airports"
          - "dest"
          - "Left"
        joinExpressions:
        - - "\"flights\".\"origin\" = \"origin\".\"iata\""
          - "flights_Left_origin"
        - - "\"flights\".\"dest\" = \"dest\".\"iata\""
          - "flights_Left_dest"
        columnMappings:
        - - "flights.flight_leg"
          - "flight_leg"
        - - "origin.airport"
          - "origin_airport"
        - - "dest.airport"
          - "dest_airport"
        - - "flights.count_1990"
          - "count_1990"
        - - "flights.avg_time_1990"
          - "avg_time_1990"
        - - "flights.count_1980"
          - "count_1980"
        - - "flights.avg_time_1980"
          - "avg_time_1980"
    Calculator 1980:
      type: "calculator"
      sources:
      - "Aggregate 1980"
      parameters:
        componentName: "Calculator 1980"
        includeInputColumns: "Yes"
        calculations:
        - - "\"origin\" || '-->' || \"dest\""
          - "flight_leg"
    Rename 1980:
      type: "rename"
      sources:
      - "Calculator 1980"
      parameters:
        componentName: "Rename 1980"
        columnMapping:
        - - "origin"
          - "origin"
        - - "dest"
          - "dest"
        - - "count_year"
          - "count_1980"
        - - "avg_actualeslapsedtime"
          - "avg_time_1980"
        - - "flight_leg"
          - "flight_leg"
    Joined Flights:
      type: "join"
      sources:
      - "Rename 1980"
      - "Rename 1990"
      parameters:
        componentName: "Joined Flights"
        mainTable: "Rename 1990"
        mainTableAlias: "90"
        joins:
        - - "Rename 1980"
          - "80"
          - "Inner"
        joinExpressions:
        - - "\"90\".\"flight_leg\" = \"80\".\"flight_leg\""
          - "90_Inner_80"
        columnMappings:
        - - "90.flight_leg"
          - "flight_leg"
        - - "90.count_1990"
          - "count_1990"
        - - "90.avg_time_1990"
          - "avg_time_1990"
        - - "80.count_1980"
          - "count_1980"
        - - "80.avg_time_1980"
          - "avg_time_1980"
        - - "90.origin"
          - "origin"
        - - "90.dest"
          - "dest"
    Aggregate 1980:
      type: "aggregate"
      sources:
      - "Filter 1980"
      parameters:
        componentName: "Aggregate 1980"
        groupings:
        - "origin"
        - "dest"
        aggregations:
        - - "year"
          - "Count"
        - - "actualeslapsedtime"
          - "Average"
        groupingType: "Group By"
    Rename 1990:
      type: "rename"
      sources:
      - "Calculator 1990"
      parameters:
        componentName: "Rename 1990"
        columnMapping:
        - - "origin"
          - "origin"
        - - "dest"
          - "dest"
        - - "count_year"
          - "count_1990"
        - - "avg_actualeslapsedtime"
          - "avg_time_1990"
        - - "flight_leg"
          - "flight_leg"
design:
  components:
    Aggregate 1990:
      position:
        x: 896
        "y": 448
      tempMetlId: 71304
    Filter 1980:
      position:
        x: 752
        "y": 352
      tempMetlId: 71306
    Calculator 1990:
      position:
        x: 1040
        "y": 448
      tempMetlId: 71307
    Read raw_flights:
      position:
        x: 464
        "y": 448
      tempMetlId: 71308
    Add Decade Column:
      position:
        x: 624
        "y": 448
      tempMetlId: 71309
    airports:
      position:
        x: 1435
        "y": 243
      tempMetlId: 71310
    Flatten airports:
      position:
        x: 1440
        "y": 352
      tempMetlId: 71311
    Table Output 0:
      position:
        x: 1680
        "y": 448
      tempMetlId: 71312
    Calculator 0:
      position:
        x: 1560
        "y": 446
      tempMetlId: 71313
    Filter 1990:
      position:
        x: 752
        "y": 448
      tempMetlId: 71314
    Join 1:
      position:
        x: 1436
        "y": 441
      tempMetlId: 71315
    Calculator 1980:
      position:
        x: 1040
        "y": 352
      tempMetlId: 71316
    Rename 1980:
      position:
        x: 1169
        "y": 353
      tempMetlId: 71317
    Joined Flights:
      position:
        x: 1296
        "y": 448
      tempMetlId: 71318
    Aggregate 1980:
      position:
        x: 899
        "y": 354
      tempMetlId: 71319
    Rename 1990:
      position:
        x: 1168
        "y": 448
      tempMetlId: 71321
