type: "orchestration"
version: "1.0"
pipeline:
  components:
    Load Airport Data:
      type: "s3-load"
      transitions:
        success:
        - "And 0"
      parameters:
        componentName: "Load Airport Data"
        stage: "[Custom]"
        authentication: "Credentials"
        s3ObjectPrefix: "s3://matillion-public/"
        pattern: "sample_jobs/airports.*"
        encryption: "None"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "airports"
        loadColumns:
        - "airport_data"
        format: "[Custom]"
        fileType: "AVRO"
        compression: "NONE"
        nullIf2:
        trimSpace2: "False"
        onError: "Abort Statement"
        sizeLimitB: ""
        purgeFiles: "False"
        matchByColumnName: "None"
        truncateColumns: "False"
        forceLoad: "True"
    Or 0:
      type: "or"
      transitions:
        unconditional:
        - "Size Down"
      parameters:
        componentName: "Or 0"
    TechWorkshop_transform:
      type: "run-transformation"
      transitions:
        success:
        - "Or 0"
        failure:
        - "Rollback"
      parameters:
        componentName: "TechWorkshop_transform"
        transformationJob: "deleteme/Tech Workshops/v1/TechWorkshop_transform"
        setScalarVariables:
        setGridVariables:
    SNS Message:
      type: "sns-message"
      transitions:
        unconditional:
        - "Or 0"
      parameters:
        componentName: "SNS Message"
        awsRegion: "eu-west-1"
        topicName: "Matillion"
        subject: "AWS Notification Message"
        message: "Your job stinks."
    Size Down:
      type: "alter-warehouse"
      parameters:
        componentName: "Size Down"
        warehouse: "[Environment Default]"
        commandType: "Set"
        properties:
        - - "WAREHOUSE_SIZE"
          - "XSMALL"
    "1990s Data":
      type: "s3-load"
      transitions:
        success:
        - "And 0"
      parameters:
        componentName: "1990s Data"
        stage: "[Custom]"
        authentication: "Credentials"
        s3ObjectPrefix: "s3://mtln-techworkshops/"
        pattern: "flights/.*"
        encryption: "None"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "raw_flights_test"
        loadColumns:
        format: "[Custom]"
        fileType: "CSV"
        compression: "AUTO"
        recordDelimiter: ""
        fieldDelimiter: ""
        skipHeader: "1"
        skipBlankLines: "False"
        dateFormat: ""
        timeFormat: ""
        timestampFormat: ""
        escape: ""
        escapeUnenclosedField: ""
        trimSpace: "False"
        fieldOptionallyEnclosed: ""
        nullIf:
        - - "NA"
        - - "\\N"
        errorOnColumnCountMismatch: "False"
        emptyFieldAsNull: "True"
        replaceInvalidCharacters: "False"
        encodingType: ""
        onError: "Continue"
        "n": ""
        sizeLimitB: ""
        purgeFiles: "False"
        truncateColumns: "False"
        forceLoad: "False"
    Rollback:
      type: "unknown-orchestration"
      transitions:
        unconditional:
        - "SNS Message"
      parameters:
        "1": "Rollback"
    Size Up:
      type: "alter-warehouse"
      transitions:
        success:
        - "raw_flights"
        - "flights_agg"
        - "airports"
      parameters:
        componentName: "Size Up"
        warehouse: "[Environment Default]"
        commandType: "Set"
        properties:
        - - "WAREHOUSE_SIZE"
          - "LARGE"
    raw_flights:
      type: "create-table"
      transitions:
        success:
        - "1990s Data"
      parameters:
        componentName: "raw_flights"
        createReplace: "Replace"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        newTableName: "raw_flights_test"
        tableType: "Permanent"
        columns:
        - - "year"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "month"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "dayofmonth"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "dayofweek"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "deptime"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "crsdeptime"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "arrtime"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "crsarrtime"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "uniquecarrier"
          - "VARCHAR"
          - "256"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "flightnum"
          - "VARCHAR"
          - "256"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "tailnum"
          - "VARCHAR"
          - "256"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "actualeslapsedtime"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "crselapsedtime"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "airtime"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "arrdelay"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "depdelay"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "origin"
          - "VARCHAR"
          - "256"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "dest"
          - "VARCHAR"
          - "256"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "distance"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "taxiin"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "taxiout"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "cancelled"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "cancellationcode"
          - "VARCHAR"
          - "256"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "diverted"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "carrierdelay"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "weatherdelay"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "nasdelay"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "securitydelay"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "lateaircraftdelay"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        defaultDdlCollation: ""
        primaryKeys:
        clusteringKeys:
        dataRetentionTimeInDays: ""
        comment: ""
    airports:
      type: "create-table"
      transitions:
        success:
        - "Load Airport Data"
      parameters:
        componentName: "airports"
        createReplace: "Replace"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        newTableName: "airports"
        tableType: "Permanent"
        columns:
        - - "airport_data"
          - "VARIANT"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - "No"
        defaultDdlCollation: ""
        primaryKeys:
        clusteringKeys:
        dataRetentionTimeInDays: ""
        comment: ""
    Start 0:
      type: "start"
      transitions:
        unconditional:
        - "Size Up"
      parameters:
        componentName: "Start 0"
    flights_agg:
      type: "create-table"
      transitions:
        success:
        - "And 0"
      parameters:
        componentName: "flights_agg"
        createReplace: "Replace"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        newTableName: "flights_agg"
        tableType: "Permanent"
        columns:
        - - "flight_leg"
          - "VARCHAR"
          - "100"
          - "0"
          - ""
          - "No"
          - "No"
        - - "origin"
          - "VARCHAR"
          - "100"
          - "0"
          - ""
          - "No"
          - "No"
        - - "dest"
          - "VARCHAR"
          - "100"
          - "0"
          - ""
          - "No"
          - "No"
        - - "count_flights_1980"
          - "VARCHAR"
          - "100"
          - "0"
          - ""
          - "No"
          - "No"
        - - "avg_elapsedflights_1980"
          - "VARCHAR"
          - "100"
          - "0"
          - ""
          - "No"
          - "No"
        - - "count_flights_1990"
          - "VARCHAR"
          - "100"
          - "0"
          - ""
          - "No"
          - "No"
        - - "avg_elapsedflights_1990"
          - "VARCHAR"
          - "100"
          - "0"
          - ""
          - "No"
          - "No"
        - - "diff_count"
          - "VARCHAR"
          - "100"
          - "0"
          - ""
          - "No"
          - "No"
        - - "diff_avgelapsedtime"
          - "VARCHAR"
          - "100"
          - "0"
          - ""
          - "No"
          - "No"
        defaultDdlCollation: ""
        primaryKeys:
        clusteringKeys:
        dataRetentionTimeInDays: ""
        comment: ""
    And 0:
      type: "and"
      transitions:
        unconditional:
        - "TechWorkshop_transform"
      parameters:
        componentName: "And 0"
  variables:
    flights_80s90s:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "flights_raw"
    flights_agg:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "flights_agg"
    query:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    mysql_connection:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "jdbc:mysql://sa-mysql-5-7-26.cq5i4y35n9gg.eu-west-"
    table:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
design:
  components:
    Load Airport Data:
      position:
        x: -32
        "y": -16
      tempMetlId: 71270
    Or 0:
      position:
        x: 672
        "y": 80
      tempMetlId: 71272
    TechWorkshop_transform:
      position:
        x: 336
        "y": 80
      tempMetlId: 71273
    SNS Message:
      position:
        x: 560
        "y": 16
      tempMetlId: 71274
    Size Down:
      position:
        x: 800
        "y": 80
      tempMetlId: 71275
    "1990s Data":
      position:
        x: -32
        "y": -112
      tempMetlId: 71276
    Rollback:
      position:
        x: 464
        "y": 16
      tempMetlId: 71277
    Size Up:
      position:
        x: -320
        "y": -16
      tempMetlId: 71278
    raw_flights:
      position:
        x: -208
        "y": -112
      tempMetlId: 71279
    airports:
      position:
        x: -208
        "y": -16
      tempMetlId: 71280
    Start 0:
      position:
        x: -432
        "y": -16
      tempMetlId: 71281
    flights_agg:
      position:
        x: -208
        "y": 80
      tempMetlId: 71282
    And 0:
      position:
        x: 224
        "y": 80
      tempMetlId: 71283
  notes:
    "71268":
      position:
        x: -94
        "y": -153
      size:
        height: 200
        width: 121
      theme: "green"
      content: "**LOAD DATA FROM S3**"
    "71269":
      position:
        x: 419
        "y": -35
      size:
        height: 163
        width: 280
      theme: "red"
      content: "**ERROR HANDLING**"
    "71271":
      position:
        x: -356
        "y": -154
      size:
        height: 282
        width: 202
      theme: "yellow"
      content: "**SNOWFLAKE SETUP**"
