type: "transformation"
version: "1.0"
pipeline:
  components:
    Join:
      type: "join"
      sources:
      - "mtln_qs_sf_account"
      - "mtln_qs_sf_contact"
      - "mtln_qs_sf_opportunity"
      - "mtln_qs_sf_opportunitycontactrole"
      parameters:
        componentName: "Join"
        mainTable: "mtln_qs_sf_opportunitycontactrole"
        mainTableAlias: "ppra1"
        joins:
        - - "mtln_qs_sf_opportunity"
          - "ppra2"
          - "Inner"
        - - "mtln_qs_sf_contact"
          - "cnta3"
          - "Inner"
        - - "mtln_qs_sf_account"
          - "ccna4"
          - "Left"
        joinExpressions:
        - - "\"ppra1\".\"OpportunityId\" = \"ppra2\".\"Id\""
          - "ppra1_Inner_ppra2"
        - - "\"ppra1\".\"ContactId\" = \"cnta3\".\"Id\""
          - "ppra1_Inner_cnta3"
        - - "\"ppra2\".\"AccountId\" = \"ccna4\".\"Id\""
          - "ppra1_Left_ccna4"
        columnMappings:
        - - "ppra1.Id"
          - "ppra1_Id"
        - - "ppra1.ContactId"
          - "ppra1_ContactId"
        - - "ppra1.OpportunityId"
          - "ppra1_OpportunityId"
        - - "ppra1.Role"
          - "ppra1_Role"
        - - "ppra1.IsPrimary"
          - "ppra1_IsPrimary"
        - - "ppra1.CreatedDate"
          - "ppra1_CreatedDate"
        - - "ppra1.LastModifiedDate"
          - "ppra1_LastModifiedDate"
        - - "ppra2.Id"
          - "ppra2_Id"
        - - "ppra2.AccountId"
          - "ppra2_AccountId"
        - - "ppra2.CloseDate"
          - "ppra2_CloseDate"
        - - "ppra2.StageName"
          - "ppra2_StageName"
        - - "ppra2.CreatedDate"
          - "ppra2_CreatedDate"
        - - "ppra2.LastModifiedDate"
          - "ppra2_LastModifiedDate"
        - - "ppra2.OwnerId"
          - "ppra2_OwnerId"
        - - "ppra2.Name"
          - "ppra2_Name"
        - - "ppra2.Description"
          - "ppra2_Description"
        - - "ppra2.Type"
          - "ppra2_Type"
        - - "cnta3.Id"
          - "cnta3_Id"
        - - "cnta3.Name"
          - "cnta3_Name"
        - - "ccna4.Id"
          - "ccna4_Id"
        - - "ccna4.Name"
          - "ccna4_Name"
        - - "ccna4.BillingCountry"
          - "ccna4_BillingCountry"
        - - "ccna4.BillingState"
          - "ccna4_BillingState"
        - - "ccna4.OwnerId"
          - "ccna4_OwnerId"
    Primary Only:
      type: "filter"
      sources:
      - "Join"
      parameters:
        componentName: "Primary Only"
        filterConditions:
        - - "ppra1_IsPrimary"
          - "Is"
          - "Equal to"
          - "tRuE"
        combineCondition: "And"
    Rewrite mtln_qs_sf_opportunity_roles_and_contacts_one_primary:
      type: "rewrite-table"
      sources:
      - "One Primary"
      parameters:
        componentName: "Rewrite mtln_qs_sf_opportunity_roles_and_contacts_one_primary"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_opportunity_roles_and_contacts_one_primary"
        orderBy:
    mtln_qs_sf_opportunitycontactrole:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_opportunitycontactrole"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_opportunitycontactrole"
        columnNames:
        - "Id"
        - "ContactId"
        - "OpportunityId"
        - "Role"
        - "IsPrimary"
        - "CreatedDate"
        - "LastModifiedDate"
        timeOffset:
    mtln_qs_sf_opportunity:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_opportunity"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_opportunity"
        columnNames:
        - "Id"
        - "AccountId"
        - "CloseDate"
        - "StageName"
        - "CreatedDate"
        - "LastModifiedDate"
        - "OwnerId"
        - "Name"
        - "Description"
        - "Type"
        timeOffset:
    mtln_qs_sf_contact:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_contact"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_contact"
        columnNames:
        - "Id"
        - "Name"
        timeOffset:
    mtln_qs_sf_account:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_account"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_account"
        columnNames:
        - "Id"
        - "Name"
        - "BillingCountry"
        - "BillingState"
        - "OwnerId"
        timeOffset:
    Rank:
      type: "rank"
      sources:
      - "Primary Only"
      parameters:
        componentName: "Rank"
        includeInputColumns: "Yes"
        partitionData:
        - "ppra1_OpportunityId"
        orderingWithinPartitions:
        - - "ppra1_CreatedDate"
          - "Ascending"
        functions:
        - - "Row Number"
          - "deduplicator"
    One Primary:
      type: "filter"
      sources:
      - "Rank"
      parameters:
        componentName: "One Primary"
        filterConditions:
        - - "deduplicator"
          - "Is"
          - "Equal to"
          - "1"
        combineCondition: "And"
design:
  components:
    Join:
      position:
        x: 150
        "y": 0
      tempMetlId: 1
    Primary Only:
      position:
        x: 300
        "y": 0
      tempMetlId: 2
    Rewrite mtln_qs_sf_opportunity_roles_and_contacts_one_primary:
      position:
        x: 700
        "y": 0
      tempMetlId: 3
    mtln_qs_sf_opportunitycontactrole:
      position:
        x: 0
        "y": -150
      tempMetlId: 4
    mtln_qs_sf_opportunity:
      position:
        x: 0
        "y": -50
      tempMetlId: 5
    mtln_qs_sf_contact:
      position:
        x: 0
        "y": 50
      tempMetlId: 6
    mtln_qs_sf_account:
      position:
        x: 0
        "y": 150
      tempMetlId: 7
    Rank:
      position:
        x: 420
        "y": 0
      tempMetlId: 8
    One Primary:
      position:
        x: 540
        "y": 0
      tempMetlId: 9
  notes:
    "1":
      position:
        x: 240
        "y": -130
      size:
        height: 200
        width: 410
      theme: "white"
      content: "Add your own filters here if you want to apply them before the integrated\
        \ report is generated"
    "2":
      position:
        x: -370
        "y": -100
      size:
        height: 100
        width: 300
      theme: "white"
      content: "Add your own Table Inputs here to customize the integration with your\
        \ own data"
