type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Run Sentiment Analysis - Acquire Review Data"
      parameters:
        componentName: "Start"
    Run Sentiment Analysis - Acquire Review Data:
      type: "run-transformation"
      transitions:
        success:
        - "Run Sentiment Analysis with Meta Llama3 70B via Amazon Bedrock"
      parameters:
        componentName: "Run Sentiment Analysis - Acquire Review Data"
        transformationJob: "Sentiment Analysis - Acquire Review Data"
        setScalarVariables:
        setGridVariables:
    Run Sentiment Analysis with Meta Llama3 70B via Amazon Bedrock:
      type: "aws-ai-prompt"
      parameters:
        componentName: "Run Sentiment Analysis with Meta Llama3 70B via Amazon Bedrock"
        aws:
          region: "us-east-1"
          modelCategory: "Meta"
          meta:
            model: "meta.llama3-70b-instruct-v1:0"
            temperature: "0.5"
            topP: "0.9"
            maxTokens: "512"
        source:
          snowflake:
            database: "[Environment Default]"
            schema: "[Environment Default]"
            table: "stg_sample_reviews"
            keyColumn: "id"
            limit: "1000"
        promptContext:
          userContext: ""
          inputs:
          - - "review"
            - "Text"
            - "Text"
          outputFormat: "JSON"
          outputs:
          - - "ai_score"
            - "Analyze the sentiment of the following text and return a score from\
              \ 1 to 5, where 1 represents the most negative sentiment and 5 represents\
              \ the most positive sentiment.\r\nRespond with a single number only.\
              \ Do not include any notes, justification, explanation or confidence\
              \ level, just the number."
        destination:
          snowflake:
            database: "[Environment Default]"
            schema: "[Environment Default]"
            table: "stg_sample_reviews_genai"
            createTableOptions: "Replace if Table Exists"
        ragConfig:
          isRagEnabled: "No"
design:
  components:
    Start:
      position:
        x: -170
        "y": 0
      tempMetlId: 1
    Run Sentiment Analysis - Acquire Review Data:
      position:
        x: -10
        "y": 0
      tempMetlId: 3
    Run Sentiment Analysis with Meta Llama3 70B via Amazon Bedrock:
      position:
        x: 140
        "y": 0
      tempMetlId: 4
  notes:
    "1":
      position:
        x: -190
        "y": -130
      size:
        height: 98
        width: 420
      theme: "white"
      content: "Perform sentiment analysis to assess a score rating based only on\
        \ product review comments"
