type: "transformation"
version: "1.0"
pipeline:
  components:
    Today's Date:
      type: "fixed-flow"
      parameters:
        componentName: "Today's Date"
        columns:
        - - "last_updated"
          - "DATE"
          - ""
          - ""
        values:
        - - "${pv_today_date}"
    Shoe Specifications:
      type: "table-input"
      parameters:
        componentName: "Shoe Specifications"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "CHARLIES_SHOE_EMPORIUM_SHOE_SPECIFICATIONS"
        columnNames:
        - "PRODUCT_NAME"
        - "PRIMARY_COLOR"
        - "SECONDARY_COLOR"
        - "PRODUCT_LINE"
        - "COMFORT"
        - "RESPONSIVENESS"
        - "WEIGHT_OZ"
        - "CUSHIONING"
        - "BREATHABILITY"
        timeOffset:
    Filter <= Today Date:
      type: "filter"
      sources:
      - "raw_charlies_shoe_emporium_sales"
      parameters:
        componentName: "Filter <= Today Date"
        filterConditions:
        - - "TRANSACTION_DATE"
          - "Is"
          - "Less than or equal to"
          - "${pv_today_date}"
        combineCondition: "And"
    raw_charlies_shoe_emporium_sales:
      type: "table-input"
      parameters:
        componentName: "raw_charlies_shoe_emporium_sales"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "RAW_CHARLIES_SHOE_EMPORIUM_SALES_${pv_state}"
        columnNames:
        - "TRANSACTION_ID"
        - "TRANSACTION_DATE"
        - "PRODUCT_NAME"
        - "SALE_INDICATOR"
        - "STORE_ID"
        - "REVIEW_INDICATOR"
        - "PRODUCT_ID"
        - "PRODUCT_PRICE"
        - "REVIEW"
        timeOffset:
    charlies_shoe_emporium_store_locations:
      type: "table-input"
      parameters:
        componentName: "charlies_shoe_emporium_store_locations"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "charlies_shoe_emporium_store_locations_${pv_state}"
        columnNames:
        - "STORE_ID"
        - "LOCATION_NAME"
        timeOffset:
    Join:
      type: "join"
      sources:
      - "Filter <= Today Date"
      - "charlies_shoe_emporium_store_locations"
      - "Today's Date"
      - "Shoe Specifications"
      parameters:
        componentName: "Join"
        mainTable: "Filter <= Today Date"
        mainTableAlias: "sales"
        joins:
        - - "charlies_shoe_emporium_store_locations"
          - "stores"
          - "Left"
        - - "Today's Date"
          - "date"
          - "Left"
        - - "Shoe Specifications"
          - "shoes"
          - "Left"
        joinExpressions:
        - - "\"sales\".\"STORE_ID\" = \"stores\".\"store_id\""
          - "sales_Left_stores"
        - - "1=1"
          - "sales_Left_date"
        - - "\"sales\".\"PRODUCT_NAME\" = \"shoes\".\"PRODUCT_NAME\""
          - "sales_Left_shoes"
        columnMappings:
        - - "date.last_updated"
          - "LAST_UPDATED"
        - - "stores.location_name"
          - "STORE_LOCATION"
        - - "sales.TRANSACTION_ID"
          - "TRANSACTION_ID"
        - - "sales.TRANSACTION_DATE"
          - "TRANSACTION_DATE"
        - - "sales.PRODUCT_NAME"
          - "PRODUCT_NAME"
        - - "sales.SALE_INDICATOR"
          - "SALE_INDICATOR"
        - - "sales.PRODUCT_PRICE"
          - "PRODUCT_PRICE"
        - - "sales.REVIEW_INDICATOR"
          - "REVIEW_INDICATOR"
        - - "sales.REVIEW"
          - "REVIEW"
        - - "shoes.PRIMARY_COLOR"
          - "PRIMARY_COLOR"
        - - "shoes.SECONDARY_COLOR"
          - "SECONDARY_COLAR"
        - - "shoes.PRODUCT_LINE"
          - "PRODUCT_LINE"
        - - "shoes.COMFORT"
          - "COMFORT"
        - - "shoes.RESPONSIVENESS"
          - "RESPONSIVENESS"
        - - "shoes.WEIGHT_OZ"
          - "WEIGHT_OZ"
        - - "shoes.CUSHIONING"
          - "CUSHIONING"
        - - "shoes.BREATHABILITY"
          - "BREATHABILITY"
    LAST_UPDATED to timestamp:
      type: "convert-type"
      sources:
      - "Join"
      parameters:
        componentName: "LAST_UPDATED to timestamp"
        conversions:
        - - "LAST_UPDATED"
          - "TIMESTAMP"
          - ""
          - ""
    Rewrite Table:
      type: "rewrite-table"
      sources:
      - "LAST_UPDATED to timestamp"
      parameters:
        componentName: "Rewrite Table"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "SRC_CHARLIES_SHOE_EMPORIUM_SALES_${pv_state}"
        orderBy:
    SRC_CHARLIES_SHOE_EMPORIUM_SALES_CO:
      type: "table-input"
      parameters:
        componentName: "SRC_CHARLIES_SHOE_EMPORIUM_SALES_CO"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "SRC_CHARLIES_SHOE_EMPORIUM_SALES_CO"
        columnNames:
        - "LAST_UPDATED"
        - "STORE_LOCATION"
        - "TRANSACTION_ID"
        - "TRANSACTION_DATE"
        - "PRODUCT_NAME"
        - "SALE_INDICATOR"
        - "PRODUCT_PRICE"
        - "REVIEW_INDICATOR"
        - "REVIEW"
        - "PRIMARY_COLOR"
        - "SECONDARY_COLAR"
        - "PRODUCT_LINE"
        - "COMFORT"
        - "RESPONSIVENESS"
        - "WEIGHT_OZ"
        - "CUSHIONING"
        - "BREATHABILITY"
        timeOffset:
    SRC_CHARLIES_SHOE_EMPORIUM_SALES_OR:
      type: "table-input"
      parameters:
        componentName: "SRC_CHARLIES_SHOE_EMPORIUM_SALES_OR"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "SRC_CHARLIES_SHOE_EMPORIUM_SALES_OR"
        columnNames:
        - "LAST_UPDATED"
        - "STORE_LOCATION"
        - "TRANSACTION_ID"
        - "TRANSACTION_DATE"
        - "PRODUCT_NAME"
        - "SALE_INDICATOR"
        - "PRODUCT_PRICE"
        - "REVIEW_INDICATOR"
        - "REVIEW"
        - "PRIMARY_COLOR"
        - "SECONDARY_COLAR"
        - "PRODUCT_LINE"
        - "COMFORT"
        - "RESPONSIVENESS"
        - "WEIGHT_OZ"
        - "CUSHIONING"
        - "BREATHABILITY"
        timeOffset:
    SRC_CHARLIES_SHOE_EMPORIUM_SALES_FL:
      type: "table-input"
      parameters:
        componentName: "SRC_CHARLIES_SHOE_EMPORIUM_SALES_FL"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "SRC_CHARLIES_SHOE_EMPORIUM_SALES_FL"
        columnNames:
        - "LAST_UPDATED"
        - "STORE_LOCATION"
        - "TRANSACTION_ID"
        - "TRANSACTION_DATE"
        - "PRODUCT_NAME"
        - "SALE_INDICATOR"
        - "PRODUCT_PRICE"
        - "REVIEW_INDICATOR"
        - "REVIEW"
        - "PRIMARY_COLOR"
        - "SECONDARY_COLAR"
        - "PRODUCT_LINE"
        - "COMFORT"
        - "RESPONSIVENESS"
        - "WEIGHT_OZ"
        - "CUSHIONING"
        - "BREATHABILITY"
        timeOffset:
  variables:
    pv_state:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "CO"
    pv_today_date:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "2024-08-19"
design:
  components:
    Today's Date:
      position:
        x: 260
        "y": 340
      tempMetlId: 3
    Shoe Specifications:
      position:
        x: 260
        "y": 440
      tempMetlId: 4
    Filter <= Today Date:
      position:
        x: 410
        "y": 120
      tempMetlId: 6
    raw_charlies_shoe_emporium_sales:
      position:
        x: 260
        "y": 120
      tempMetlId: 7
    charlies_shoe_emporium_store_locations:
      position:
        x: 260
        "y": 230
      tempMetlId: 8
    Join:
      position:
        x: 540
        "y": 230
      tempMetlId: 12
    LAST_UPDATED to timestamp:
      position:
        x: 680
        "y": 230
      tempMetlId: 13
    Rewrite Table:
      position:
        x: 840
        "y": 230
      tempMetlId: 14
    SRC_CHARLIES_SHOE_EMPORIUM_SALES_CO:
      position:
        x: 1010
        "y": 230
      tempMetlId: 15
    SRC_CHARLIES_SHOE_EMPORIUM_SALES_OR:
      position:
        x: 1010
        "y": 360
      tempMetlId: 16
    SRC_CHARLIES_SHOE_EMPORIUM_SALES_FL:
      position:
        x: 1010
        "y": 120
      tempMetlId: 17
