type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "dbt Core"
      parameters:
        componentName: "Start"
    dbt Core:
      type: "commands-for-dbt-core"
      parameters:
        componentName: "dbt Core"
        command: "dbt build --select 3-crossing-finish-line"
        dbtUrl: "https://github.com/MatillionPartnerEngineering/Stepping-into-Data-with-Matillion-and-dbt/"
        branch: "crossing"
        gitFolderPath:
        userName: "partnersuccess@matillion.com"
        gitPassword: "kg_github_cnverttoken"
        mapDbtEnvironmentVariables:
        - - "DBT_TARGET_DATABASE"
          - "DEV_DB"
        - - "DBT_TARGET_SCHEMA"
          - "KAREY"
        config:
        profileConfig:
design:
  components:
    Start:
      position:
        x: -80
        "y": 10
      tempMetlId: 1
    dbt Core:
      position:
        x: 40
        "y": 10
      tempMetlId: 2
  notes:
    "1":
      position:
        x: -100
        "y": -140
      size:
        height: 128
        width: 300
      theme: "white"
      content: |-
        - Incremental loading
        - Grid variables
        - Cortex
        - dbt docs
        - output components
