type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Grid Iterator"
        - "Grid Iterator 3"
      parameters:
        componentName: "Start"
    S3 Load charlies_shoe_emporium_sales:
      type: "s3-load"
      parameters:
        componentName: "S3 Load charlies_shoe_emporium_sales"
        stage: "[Custom]"
        authentication: "Credentials"
        s3ObjectPrefix: "s3://mtln-techworkshops/"
        pattern: "charlies_shoe_emporium/charlies_shoe_emporium_sales_${pv_state}.csv"
        encryption: "None"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "RAW_CHARLIES_SHOE_EMPORIUM_SALES_${pv_state}"
        loadColumns:
        format: "[Custom]"
        fileType: "CSV"
        compression: "AUTO"
        recordDelimiter:
        fieldDelimiter:
        skipHeader: "1"
        skipBlankLines: "False"
        dateFormat:
        timeFormat:
        timestampFormat:
        escape:
        escapeUnenclosedField:
        trimSpace: "False"
        fieldOptionallyEnclosed:
        nullIf:
        errorOnColumnCountMismatch: "False"
        emptyFieldAsNull: "True"
        replaceInvalidCharacters: "False"
        encodingType:
        onError: "Abort Statement"
        sizeLimitB:
        purgeFiles: "False"
        truncateColumns: "False"
        forceLoad: "False"
    Create Table charlies_shoe_emporium_sales:
      type: "create-table"
      parameters:
        componentName: "Create Table charlies_shoe_emporium_sales"
        createReplace: "Replace"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        newTableName: "RAW_CHARLIES_SHOE_EMPORIUM_SALES_${pv_state}"
        tableType: "Permanent"
        columns:
        - - "TRANSACTION_ID"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "TRANSACTION_DATE"
          - "DATE"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "PRODUCT_NAME"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "SALE_INDICATOR"
          - "BOOLEAN"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "STORE_ID"
          - "NUMBER"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "REVIEW_INDICATOR"
          - "BOOLEAN"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "PRODUCT_ID"
          - "NUMBER"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "PRODUCT_PRICE"
          - "NUMBER"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "REVIEW"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        defaultDdlCollation:
        primaryKeys:
        clusteringKeys:
        dataRetentionTimeInDays:
        comment:
    S3 Load charlies_shoe_emporium_store_locations:
      type: "s3-load"
      parameters:
        componentName: "S3 Load charlies_shoe_emporium_store_locations"
        stage: "[Custom]"
        authentication: "Credentials"
        s3ObjectPrefix: "s3://mtln-techworkshops/"
        pattern: "charlies_shoe_emporium/charlies_shoe_emporium_store_locations_${pv_state}.csv"
        encryption: "None"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "CHARLIES_SHOE_EMPORIUM_STORE_LOCATIONS_${pv_state}"
        loadColumns:
        format: "[Custom]"
        fileType: "CSV"
        compression: "AUTO"
        recordDelimiter:
        fieldDelimiter:
        skipHeader: "1"
        skipBlankLines: "False"
        dateFormat:
        timeFormat:
        timestampFormat:
        escape:
        escapeUnenclosedField:
        trimSpace: "False"
        fieldOptionallyEnclosed:
        nullIf:
        errorOnColumnCountMismatch: "False"
        emptyFieldAsNull: "True"
        replaceInvalidCharacters: "False"
        encodingType:
        onError: "Abort Statement"
        sizeLimitB:
        purgeFiles: "False"
        truncateColumns: "False"
        forceLoad: "False"
    Create Table charlies_shoe_emporium_store_locations:
      type: "create-table"
      parameters:
        componentName: "Create Table charlies_shoe_emporium_store_locations"
        createReplace: "Replace"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        newTableName: "CHARLIES_SHOE_EMPORIUM_STORE_LOCATIONS_${pv_state}"
        tableType: "Permanent"
        columns:
        - - "STORE_ID"
          - "NUMBER"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "LOCATION_NAME"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        defaultDdlCollation:
        primaryKeys:
        clusteringKeys:
        dataRetentionTimeInDays:
        comment:
    Get Today Date - 5 days:
      type: "python-pushdown"
      transitions:
        success:
        - "Grid Iterator 5"
      parameters:
        componentName: "Get Today Date - 5 days"
        externalAccessIntegrations:
        packages:
        pythonScript: |
          from datetime import datetime, timedelta

          # Get today's date
          today = datetime.now()

          #subtract 5 days
          yesterday = today - timedelta(days=5)

          # Format yesterday's date
          formatted_yesterday = yesterday.strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]

          print(formatted_yesterday)

          context.updateVariable('pv_today_date', formatted_yesterday)

          print(pv_today_date)
          # Updating a grid variable:
          #   context.updateGridVariable('mygridvar',[['list','of'],['lists','!']])
          ###)
        scriptTimeout: "360"
    And:
      type: "and"
      transitions:
        unconditional:
        - "Get Today Date - 5 days"
      parameters:
        componentName: "And"
    Run charlie CO OR incremental load xform:
      type: "run-transformation"
      parameters:
        componentName: "Run charlie CO OR incremental load xform"
        transformationJob: "Labs/Stepping into Data with Matillion and dbt/3-Crossing\
          \ the Finish Line/charlie incremental load xform"
        setScalarVariables:
        - - "pv_today_date"
          - "${pv_today_date}"
        - - "pv_state"
          - "${pv_state}"
        setGridVariables:
    Grid Iterator:
      type: "grid-iterator"
      transitions:
        success:
        - "Grid Iterator 2"
      iterationTarget: "Create Table charlies_shoe_emporium_store_locations"
      parameters:
        componentName: "Grid Iterator"
        gridVariable: "gv_state_list"
        gridIteratorVariableMapping:
        - - "gvc_state_list"
          - "pv_state"
        breakOnFailure: "No"
        concurrency: "Sequential"
    Grid Iterator 2:
      type: "grid-iterator"
      transitions:
        success:
        - "And"
      iterationTarget: "S3 Load charlies_shoe_emporium_store_locations"
      parameters:
        componentName: "Grid Iterator 2"
        gridVariable: "gv_state_list"
        gridIteratorVariableMapping:
        - - "gvc_state_list"
          - "pv_state"
        breakOnFailure: "No"
        concurrency: "Sequential"
    Grid Iterator 3:
      type: "grid-iterator"
      transitions:
        success:
        - "Grid Iterator 4"
      iterationTarget: "Create Table charlies_shoe_emporium_sales"
      parameters:
        componentName: "Grid Iterator 3"
        gridVariable: "gv_state_list"
        gridIteratorVariableMapping:
        - - "gvc_state_list"
          - "pv_state"
        breakOnFailure: "No"
        concurrency: "Sequential"
    Grid Iterator 4:
      type: "grid-iterator"
      transitions:
        success:
        - "And"
      iterationTarget: "S3 Load charlies_shoe_emporium_sales"
      parameters:
        componentName: "Grid Iterator 4"
        gridVariable: "gv_state_list"
        gridIteratorVariableMapping:
        - - "gvc_state_list"
          - "pv_state"
        breakOnFailure: "No"
        concurrency: "Sequential"
    Grid Iterator 5:
      type: "grid-iterator"
      iterationTarget: "Run charlie CO OR incremental load xform"
      parameters:
        componentName: "Grid Iterator 5"
        gridVariable: "gv_state_list"
        gridIteratorVariableMapping:
        - - "gvc_state_list"
          - "pv_state"
        breakOnFailure: "No"
        concurrency: "Sequential"
  variables:
    pv_state:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "CO"
    pv_today_date:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "1900-01-01"
    gv_state_list:
      metadata:
        type: "GRID"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
        columns:
          gvc_state_list:
            columnType: "TEXT"
      defaultValue:
      - - "CO"
      - - "OR"
design:
  components:
    Start:
      position:
        x: -110
        "y": 0
      tempMetlId: 1
    S3 Load charlies_shoe_emporium_sales:
      position:
        x: 340
        "y": -10
      tempMetlId: 2
    Create Table charlies_shoe_emporium_sales:
      position:
        x: 150
        "y": -10
      tempMetlId: 3
    S3 Load charlies_shoe_emporium_store_locations:
      position:
        x: 340
        "y": 140
      tempMetlId: 6
    Create Table charlies_shoe_emporium_store_locations:
      position:
        x: 150
        "y": 140
      tempMetlId: 7
    Get Today Date - 5 days:
      position:
        x: 720
        "y": 0
      tempMetlId: 9
    And:
      position:
        x: 570
        "y": 0
      tempMetlId: 11
    Run charlie CO OR incremental load xform:
      position:
        x: 900
        "y": -10
      tempMetlId: 12
    Grid Iterator:
      position:
        x: 150
        "y": 140
      tempMetlId: 13
    Grid Iterator 2:
      position:
        x: 340
        "y": 140
      tempMetlId: 14
    Grid Iterator 3:
      position:
        x: 150
        "y": -10
      tempMetlId: 15
    Grid Iterator 4:
      position:
        x: 340
        "y": -10
      tempMetlId: 16
    Grid Iterator 5:
      position:
        x: 900
        "y": -10
      tempMetlId: 17
