type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Create Table STORE_GM_NAMES"
        - "Create Table charlies_shoe_emporium_shoe_specifications"
        - "Create Table charlies_shoe_emporium_sales"
        - "Create Table charlies_shoe_emporium_store_locations"
      skipped: false
      parameters:
        componentName: "Start"
    S3 Load charlies_shoe_emporium_sales:
      type: "s3-load"
      skipped: false
      parameters:
        componentName: "S3 Load charlies_shoe_emporium_sales"
        stage: "[Custom]"
        authentication: "Credentials"
        s3ObjectPrefix: "s3://mtln-techworkshops/"
        pattern: "charlies_shoe_emporium/charlies_shoe_emporium_sales_${pv_state}.csv"
        encryption: "None"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "RAW_CHARLIES_SHOE_EMPORIUM_SALES"
        loadColumns:
        format: "[Custom]"
        fileType: "CSV"
        compression: "AUTO"
        recordDelimiter:
        fieldDelimiter:
        skipHeader: "1"
        skipBlankLines: "False"
        dateFormat:
        timeFormat:
        timestampFormat:
        escape:
        escapeUnenclosedField:
        trimSpace: "False"
        fieldOptionallyEnclosed:
        nullIf:
        errorOnColumnCountMismatch: "False"
        emptyFieldAsNull: "True"
        replaceInvalidCharacters: "False"
        encodingType:
        onError: "Abort Statement"
        sizeLimitB:
        purgeFiles: "False"
        truncateColumns: "False"
        forceLoad: "False"
    Create Table charlies_shoe_emporium_sales:
      type: "create-table"
      transitions:
        success:
        - "Grid Iterator 4"
      skipped: false
      parameters:
        componentName: "Create Table charlies_shoe_emporium_sales"
        createReplace: "Replace"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        newTableName: "RAW_CHARLIES_SHOE_EMPORIUM_SALES"
        tableType: "Permanent"
        columns:
        - - "TRANSACTION_ID"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "TRANSACTION_DATE"
          - "DATE"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "PRODUCT_NAME"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "SALE_INDICATOR"
          - "BOOLEAN"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "STORE_ID"
          - "NUMBER"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "REVIEW_INDICATOR"
          - "BOOLEAN"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "PRODUCT_ID"
          - "NUMBER"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "PRODUCT_PRICE"
          - "NUMBER"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "REVIEW"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        defaultDdlCollation:
        primaryKeys:
        clusteringKeys:
        dataRetentionTimeInDays:
        comment:
    S3 Load charlies_shoe_emporium_store_locations:
      type: "s3-load"
      skipped: false
      parameters:
        componentName: "S3 Load charlies_shoe_emporium_store_locations"
        stage: "[Custom]"
        authentication: "Credentials"
        s3ObjectPrefix: "s3://mtln-techworkshops/"
        pattern: "charlies_shoe_emporium/charlies_shoe_emporium_store_locations_${pv_state}.csv"
        encryption: "None"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "CHARLIES_SHOE_EMPORIUM_STORE_LOCATIONS"
        loadColumns:
        format: "[Custom]"
        fileType: "CSV"
        compression: "AUTO"
        recordDelimiter:
        fieldDelimiter:
        skipHeader: "1"
        skipBlankLines: "False"
        dateFormat:
        timeFormat:
        timestampFormat:
        escape:
        escapeUnenclosedField:
        trimSpace: "False"
        fieldOptionallyEnclosed:
        nullIf:
        errorOnColumnCountMismatch: "False"
        emptyFieldAsNull: "True"
        replaceInvalidCharacters: "False"
        encodingType:
        onError: "Abort Statement"
        sizeLimitB:
        purgeFiles: "False"
        truncateColumns: "False"
        forceLoad: "False"
    Create Table charlies_shoe_emporium_store_locations:
      type: "create-table"
      transitions:
        success:
        - "Grid Iterator 2"
      skipped: false
      parameters:
        componentName: "Create Table charlies_shoe_emporium_store_locations"
        createReplace: "Replace"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        newTableName: "CHARLIES_SHOE_EMPORIUM_STORE_LOCATIONS"
        tableType: "Permanent"
        columns:
        - - "STORE_ID"
          - "NUMBER"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "LOCATION_NAME"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        defaultDdlCollation:
        primaryKeys:
        clusteringKeys:
        dataRetentionTimeInDays:
        comment:
    And:
      type: "and"
      skipped: false
      parameters:
        componentName: "And"
    Grid Iterator 2:
      type: "grid-iterator"
      transitions:
        success:
        - "And"
      iterationTarget: "S3 Load charlies_shoe_emporium_store_locations"
      skipped: false
      parameters:
        componentName: "Grid Iterator 2"
        gridVariable: "gv_state_list"
        gridIteratorVariableMapping:
        - - "gvc_state_list"
          - "pv_state"
        breakOnFailure: "No"
        concurrency: "Sequential"
    Grid Iterator 4:
      type: "grid-iterator"
      transitions:
        success:
        - "And"
      iterationTarget: "S3 Load charlies_shoe_emporium_sales"
      skipped: false
      parameters:
        componentName: "Grid Iterator 4"
        gridVariable: "gv_state_list"
        gridIteratorVariableMapping:
        - - "gvc_state_list"
          - "pv_state"
        breakOnFailure: "No"
        concurrency: "Sequential"
    Create Table charlies_shoe_emporium_shoe_specifications:
      type: "create-table"
      transitions:
        success:
        - "S3 Load charlies_shoe_emporium_shoe_specifications"
      skipped: false
      parameters:
        componentName: "Create Table charlies_shoe_emporium_shoe_specifications"
        createReplace: "Replace"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        newTableName: "CHARLIES_SHOE_EMPORIUM_SHOE_SPECIFICATIONS"
        tableType: "Permanent"
        columns:
        - - "PRODUCT_NAME"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "PRIMARY_COLOR"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "SECONDARY_COLOR"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "PRODUCT_LINE"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "COMFORT"
          - "FLOAT"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "RESPONSIVENESS"
          - "FLOAT"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "WEIGHT_OZ"
          - "FLOAT"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "CUSHIONING"
          - "FLOAT"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "BREATHABILITY"
          - "FLOAT"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        defaultDdlCollation:
        primaryKeys:
        clusteringKeys:
        dataRetentionTimeInDays:
        comment:
    S3 Load charlies_shoe_emporium_shoe_specifications:
      type: "s3-load"
      transitions:
        success:
        - "And"
      skipped: false
      parameters:
        componentName: "S3 Load charlies_shoe_emporium_shoe_specifications"
        stage: "[Custom]"
        authentication: "Credentials"
        s3ObjectPrefix: "s3://mtln-techworkshops/"
        pattern: "charlies_shoe_emporium/charlies_shoe_emporium_shoe_specifications.csv"
        encryption: "None"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "CHARLIES_SHOE_EMPORIUM_SHOE_SPECIFICATIONS"
        loadColumns:
        format: "[Custom]"
        fileType: "CSV"
        compression: "AUTO"
        recordDelimiter:
        fieldDelimiter:
        skipHeader: "1"
        skipBlankLines: "False"
        dateFormat:
        timeFormat:
        timestampFormat:
        escape:
        escapeUnenclosedField:
        trimSpace: "False"
        fieldOptionallyEnclosed:
        nullIf:
        errorOnColumnCountMismatch: "False"
        emptyFieldAsNull: "True"
        replaceInvalidCharacters: "False"
        encodingType:
        onError: "Abort Statement"
        sizeLimitB:
        purgeFiles: "False"
        truncateColumns: "False"
        forceLoad: "False"
    Create Table STORE_GM_NAMES:
      type: "create-table"
      transitions:
        success:
        - "S3 Load STORE_GM_NAMES"
      skipped: false
      parameters:
        componentName: "Create Table STORE_GM_NAMES"
        createReplace: "Replace"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        newTableName: "STORE_GM_NAMES"
        tableType: "Permanent"
        columns:
        - - "STORE_ID"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "GM_NAME"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        defaultDdlCollation:
        primaryKeys:
        clusteringKeys:
        dataRetentionTimeInDays:
        comment:
    S3 Load STORE_GM_NAMES:
      type: "s3-load"
      transitions:
        success:
        - "And"
      skipped: false
      parameters:
        componentName: "S3 Load STORE_GM_NAMES"
        stage: "[Custom]"
        authentication: "Credentials"
        s3ObjectPrefix: "s3://mtln-techworkshops/"
        pattern: "charlies_shoe_emporium/store_gm_names.csv"
        encryption: "None"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "STORE_GM_NAMES"
        loadColumns:
        format: "[Custom]"
        fileType: "CSV"
        compression: "AUTO"
        recordDelimiter:
        fieldDelimiter:
        skipHeader: "1"
        skipBlankLines: "False"
        dateFormat:
        timeFormat:
        timestampFormat:
        escape:
        escapeUnenclosedField:
        trimSpace: "False"
        fieldOptionallyEnclosed:
        nullIf:
        errorOnColumnCountMismatch: "False"
        emptyFieldAsNull: "True"
        replaceInvalidCharacters: "False"
        encodingType:
        onError: "Abort Statement"
        sizeLimitB:
        purgeFiles: "False"
        truncateColumns: "False"
        forceLoad: "False"
  variables:
    pv_state:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "CO"
    pv_today_date:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "1900-01-01"
    gv_state_list:
      metadata:
        type: "GRID"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
        columns:
          gvc_state_list:
            columnType: "TEXT"
      defaultValue:
      - - "FL"
      - - "CO"
      - - "OR"
design:
  components:
    Start:
      position:
        x: -60
        "y": -50
      tempMetlId: 1
    S3 Load charlies_shoe_emporium_sales:
      position:
        x: 340
        "y": -10
      tempMetlId: 2
    Create Table charlies_shoe_emporium_sales:
      position:
        x: 150
        "y": 0
      tempMetlId: 3
    S3 Load charlies_shoe_emporium_store_locations:
      position:
        x: 340
        "y": 120
      tempMetlId: 6
    Create Table charlies_shoe_emporium_store_locations:
      position:
        x: 150
        "y": 130
      tempMetlId: 7
    And:
      position:
        x: 570
        "y": -50
      tempMetlId: 11
    Grid Iterator 2:
      position:
        x: 340
        "y": 120
      tempMetlId: 14
    Grid Iterator 4:
      position:
        x: 340
        "y": -10
      tempMetlId: 16
    Create Table charlies_shoe_emporium_shoe_specifications:
      position:
        x: 150
        "y": -120
      tempMetlId: 18
    S3 Load charlies_shoe_emporium_shoe_specifications:
      position:
        x: 340
        "y": -120
      tempMetlId: 19
    Create Table STORE_GM_NAMES:
      position:
        x: 150
        "y": -230
      tempMetlId: 20
    S3 Load STORE_GM_NAMES:
      position:
        x: 340
        "y": -230
      tempMetlId: 21
