type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Run load charlies_shoe_emporium data"
      parameters:
        componentName: "Start"
    'Superpower Set #1':
      type: "run-orchestration"
      transitions:
        success:
        - "Superpower Set #2"
      parameters:
        componentName: "Superpower Set #1"
        orchestrationJob: "Labs/Powered Up Pipelines/Completed Work/2 - Superpower\
          \ Group 1/incremental load"
        setScalarVariables:
        setGridVariables:
    'Superpower Set #2':
      type: "run-orchestration"
      transitions:
        success:
        - "Superpower Set #3"
      parameters:
        componentName: "Superpower Set #2"
        orchestrationJob: "Labs/Powered Up Pipelines/Completed Work/3 - Superpower\
          \ Group 2/dbt_tests"
        setScalarVariables:
        setGridVariables:
    'Superpower Set #3':
      type: "run-orchestration"
      parameters:
        componentName: "Superpower Set #3"
        orchestrationJob: "Labs/Powered Up Pipelines/Completed Work/4 - Superpower\
          \ Group 3/cortex cleanup orch"
        setScalarVariables:
        setGridVariables:
    Run load charlies_shoe_emporium data:
      type: "run-orchestration"
      transitions:
        success:
        - "Superpower Set #1"
      parameters:
        componentName: "Run load charlies_shoe_emporium data"
        orchestrationJob: "Labs/Powered Up Pipelines/Completed Work/1 - Prep Data/load\
          \ charlies_shoe_emporium data"
        setScalarVariables:
        setGridVariables:
design:
  components:
    Start:
      position:
        x: -170
        "y": 0
      tempMetlId: 1
    'Superpower Set #1':
      position:
        x: 180
        "y": 0
      tempMetlId: 2
    'Superpower Set #2':
      position:
        x: 380
        "y": 0
      tempMetlId: 3
    'Superpower Set #3':
      position:
        x: 580
        "y": 0
      tempMetlId: 4
    Run load charlies_shoe_emporium data:
      position:
        x: -20
        "y": 0
      tempMetlId: 5
