type: "transformation"
version: "1.0"
pipeline:
  components:
    stg_aws_rss_feed:
      type: "table-input"
      parameters:
        componentName: "stg_aws_rss_feed"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "stg_aws_rss_feed"
        columnNames:
        - "channel"
        timeOffset:
    XML to JSON using UDF:
      type: "calculator"
      sources:
      - "stg_aws_rss_feed"
      parameters:
        componentName: "XML to JSON using UDF"
        includeInputColumns: "No"
        calculations:
        - - "PARSE_JSON(XML_TO_JSON(\"channel\"::VARCHAR))"
          - "json"
    Extract Nested Data:
      type: "extract-nested-data-sf"
      sources:
      - "XML to JSON using UDF"
      parameters:
        componentName: "Extract Nested Data"
        includeInputColumns: "No"
        columns:
        - name: "channel['atom:link']['@href']"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "json"
          aliasName: "channel['atom:link']['@href']"
          isArray: "false"
          include: "false"
        - name: "channel['atom:link']"
          datatype: "VARIANT"
          size: "0"
          decimalPlaces: "0"
          columnName: "json"
          aliasName: "channel['atom:link']"
          isArray: "false"
          include: "false"
        - name: "channel['atom:link']['@rel']"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "json"
          aliasName: "channel['atom:link']['@rel']"
          isArray: "false"
          include: "false"
        - name: "channel['sy:updatePeriod']"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "json"
          aliasName: "channel['sy:updatePeriod']"
          isArray: "false"
          include: "false"
        - name: "channel"
          datatype: "VARIANT"
          size: "0"
          decimalPlaces: "0"
          columnName: "json"
          aliasName: "channel"
          isArray: "false"
          include: "false"
          childElements:
          - name: "lastBuildDate"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "json"
            aliasName: "lastBuildDate"
            isArray: "false"
            include: "false"
          - name: "language"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "json"
            aliasName: "language"
            isArray: "false"
            include: "false"
          - name: "item"
            datatype: "VARIANT"
            size: "0"
            decimalPlaces: "0"
            columnName: "json"
            aliasName: "item"
            isArray: "true"
            include: "false"
            childElements:
            - name: "item-element"
              datatype: "VARIANT"
              size: "0"
              decimalPlaces: "0"
              columnName: "json"
              aliasName: "item-element"
              isArray: "false"
              include: "false"
              childElements:
              - name: "title"
                datatype: "VARCHAR"
                size: "0"
                decimalPlaces: "0"
                columnName: "json"
                aliasName: "TITLE"
                isArray: "false"
                include: "true"
              - name: "category"
                datatype: "VARIANT"
                size: "0"
                decimalPlaces: "0"
                columnName: "json"
                aliasName: "category"
                isArray: "true"
                include: "false"
                childElements:
                - name: "category-element"
                  datatype: "VARCHAR"
                  size: "0"
                  decimalPlaces: "0"
                  columnName: "json"
                  aliasName: "category-element"
                  isArray: "false"
                  include: "false"
              - name: "link"
                datatype: "VARCHAR"
                size: "0"
                decimalPlaces: "0"
                columnName: "json"
                aliasName: "channel_item-element_link"
                isArray: "false"
                include: "false"
              - name: "description"
                datatype: "VARCHAR"
                size: "0"
                decimalPlaces: "0"
                columnName: "json"
                aliasName: "DESCRIPTION"
                isArray: "false"
                include: "true"
              - name: "pubDate"
                datatype: "DATE"
                size: "0"
                decimalPlaces: "0"
                columnName: "json"
                aliasName: "PUBDATE"
                isArray: "false"
                include: "true"
              - name: "guid\".\"#text"
                datatype: "VARCHAR"
                size: "80"
                decimalPlaces: "0"
                columnName: "json"
                aliasName: "GUID"
                isArray: "false"
                include: "true"
              - name: "guid['@isPermaLink']"
                datatype: "VARCHAR"
                size: "0"
                decimalPlaces: "0"
                columnName: "json"
                aliasName: "guid['@isPermaLink']"
                isArray: "false"
                include: "false"
              - name: "guid['#text']"
                datatype: "VARCHAR"
                size: "0"
                decimalPlaces: "0"
                columnName: "json"
                aliasName: "guid['#text']"
                isArray: "false"
                include: "false"
          - name: "item[]['content:encoded']"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "json"
            aliasName: "item[]['content:encoded']"
            isArray: "false"
            include: "false"
          - name: "item[]['dc:creator']"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "json"
            aliasName: "item[]['dc:creator']"
            isArray: "false"
            include: "false"
          - name: "link"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "json"
            aliasName: "channel_link"
            isArray: "false"
            include: "false"
          - name: "title"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "json"
            aliasName: "channel_title"
            isArray: "false"
            include: "false"
          - name: "description"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "json"
            aliasName: "channel_description"
            isArray: "false"
            include: "false"
        - name: "channel['sy:updateFrequency']"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "json"
          aliasName: "channel['sy:updateFrequency']"
          isArray: "false"
          include: "false"
        - name: "channel['atom:link']['@type']"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "json"
          aliasName: "channel['atom:link']['@type']"
          isArray: "false"
          include: "false"
        outerJoin: "No"
        inputAlias: "i"
        arrayPrefix: "f"
        castingMethod: "Fail on invalid data"
        caseColumnAliasNames: "No"
    aws_rss_feed:
      type: "table-update"
      sources:
      - "Extract Nested Data"
      parameters:
        componentName: "aws_rss_feed"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "aws_rss_feed"
        targetAlias: "target"
        sourceAlias: "input"
        joinExpression:
        - - "\"input\".\"GUID\" = \"target\".\"GUID\""
          - "Case"
        whenMatched:
        - - "true"
          - "Update"
        updateMapping:
        - - "TITLE"
          - "TITLE"
        - - "DESCRIPTION"
          - "DESCRIPTION"
        - - "PUBDATE"
          - "PUBDATE"
        includeNotMatched: "Yes"
        insertMapping:
        - - "GUID"
          - "GUID"
        - - "TITLE"
          - "TITLE"
        - - "DESCRIPTION"
          - "DESCRIPTION"
        - - "PUBDATE"
          - "PUBDATE"
design:
  components:
    stg_aws_rss_feed:
      position:
        x: -30
        "y": 0
      tempMetlId: 1
    XML to JSON using UDF:
      position:
        x: 130
        "y": 0
      tempMetlId: 2
    Extract Nested Data:
      position:
        x: 290
        "y": 0
      tempMetlId: 3
    aws_rss_feed:
      position:
        x: 440
        "y": 0
      tempMetlId: 4
  notes:
    "1":
      position:
        x: 110
        "y": -170
      size:
        height: 138
        width: 380
      theme: "light-green"
      content: |-
        Flatten all the <item>s from the RSS feed, and merge them into the permanent target table.

        Once the data is in JSON format it's possible to use Extract Nested Data
