type: "transformation"
version: "1.0"
pipeline:
  components:
    Raw Barista reviews:
      type: "table-input"
      parameters:
        componentName: "Raw Barista reviews"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "STG_BARISTA_REVIEWS"
        columnNames:
        - "name"
        - "location"
        - "date"
        - "rating"
        - "review"
        timeOffset:
    AI-processed Barista Reviews:
      type: "table-input"
      parameters:
        componentName: "AI-processed Barista Reviews"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "BARISTA_REVIEWS_PROCESSED_OPENAI"
        columnNames:
        - "name"
        - "DATA"
        - "PROMPT_TOKENS"
        - "COMPLETION_TOKENS"
        - "ALL_TOKENS"
        - "RAW_DATA"
        - "ERROR_METADATA"
        - "SYSTEM_PROMPT"
        - "USER_PROMPT"
        - "MODEL_NAME"
        - "PROVIDER_NAME"
        timeOffset:
    Extract new columns generated by AI:
      type: "extract-nested-data-sf"
      sources:
      - "AI-processed Barista Reviews"
      parameters:
        componentName: "Extract new columns generated by AI"
        includeInputColumns: "Yes"
        columns:
        - name: "anger_score"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "DATA"
          aliasName: "anger_score"
          isArray: "false"
          include: "true"
        - name: "anger_reason"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "DATA"
          aliasName: "anger_reason"
          isArray: "false"
          include: "true"
        - name: "sentiment"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "DATA"
          aliasName: "sentiment"
          isArray: "false"
          include: "true"
        - name: "anger_summary"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "DATA"
          aliasName: "anger_summary"
          isArray: "false"
          include: "true"
        - name: "swear_words"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "DATA"
          aliasName: "swear_words"
          isArray: "false"
          include: "true"
        - name: "product_involved"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "DATA"
          aliasName: "product_involved"
          isArray: "false"
          include: "true"
        - name: "wont_return"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "DATA"
          aliasName: "wont_return"
          isArray: "false"
          include: "true"
        outerJoin: "No"
        inputAlias: "i"
        arrayPrefix: "f"
        castingMethod: "Fail on invalid data"
        caseColumnAliasNames: "No"
    Integrate raw reviews and AI-processed reviews:
      type: "join"
      sources:
      - "Raw Barista reviews"
      - "Extract new columns generated by AI"
      parameters:
        componentName: "Integrate raw reviews and AI-processed reviews"
        mainTable: "Raw Barista reviews"
        mainTableAlias: "raw"
        joins:
        - - "Extract new columns generated by AI"
          - "processed"
          - "Left"
        joinExpressions:
        - - "\"raw\".\"name\" = \"processed\".\"name\""
          - "raw_Left_processed"
        columnMappings:
        - - "processed.name"
          - "processed_name"
        - - "processed.anger_score"
          - "anger_score"
        - - "processed.anger_reason"
          - "anger_reason"
        - - "processed.sentiment"
          - "sentiment"
        - - "processed.anger_summary"
          - "anger_summary"
        - - "processed.swear_words"
          - "swear_words"
        - - "processed.product_involved"
          - "product_involved"
        - - "processed.wont_return"
          - "wont_return"
        - - "raw.location"
          - "location"
        - - "raw.rating"
          - "rating"
        - - "raw.review"
          - "review"
    Barista reviews with GenAI columns for analytics:
      type: "rewrite-table"
      sources:
      - "Integrate raw reviews and AI-processed reviews"
      parameters:
        componentName: "Barista reviews with GenAI columns for analytics"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "BARISTA_REVIEWS_FINAL"
        orderBy:
design:
  components:
    Raw Barista reviews:
      position:
        x: -350
        "y": 0
      tempMetlId: 1
    AI-processed Barista Reviews:
      position:
        x: -530
        "y": 120
      tempMetlId: 2
    Extract new columns generated by AI:
      position:
        x: -345
        "y": 120
      tempMetlId: 3
    Integrate raw reviews and AI-processed reviews:
      position:
        x: -160
        "y": 60
      tempMetlId: 4
    Barista reviews with GenAI columns for analytics:
      position:
        x: 30
        "y": 60
      tempMetlId: 6
  notes:
    "1":
      position:
        x: -700
        "y": -60
      size:
        height: 128
        width: 250
      theme: "light-green"
      content: "Create `BARISTA_REVIEWS_FINAL` by integrating the original unstructured\
        \ text review data with the AI-generated results"
