type: "transformation"
version: "1.0"
pipeline:
  components:
    mtln_qs_sf_account:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_account"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_account"
        columnNames:
        - "Id"
        - "Name"
        - "AnnualRevenue"
        - "LastModifiedDate"
        timeOffset:
    Rank:
      type: "rank"
      sources:
      - "mtln_qs_sf_account"
      parameters:
        componentName: "Rank"
        includeInputColumns: "Yes"
        partitionData:
        - "Id"
        orderingWithinPartitions:
        - - "LastModifiedDate"
          - "Descending"
        functions:
        - - "Row Number"
          - "rn"
    Filter:
      type: "filter"
      sources:
      - "Rank"
      parameters:
        componentName: "Filter"
        filterConditions:
        - - "rn"
          - "Is"
          - "Equal to"
          - "1"
        combineCondition: "And"
    Rename:
      type: "rename"
      sources:
      - "Filter"
      parameters:
        componentName: "Rename"
        columnMapping:
        - - "Id"
          - "id"
        - - "Name"
          - "account_name"
        - - "AnnualRevenue"
          - "annual_revenue"
        - - "LastModifiedDate"
          - "last_modified_timestamp"
        includeInputColumns: "No"
    mtln_qs_sf_ods_account:
      type: "table-update"
      sources:
      - "Rename"
      parameters:
        componentName: "mtln_qs_sf_ods_account"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_ods_account"
        targetAlias: "target"
        sourceAlias: "input"
        joinExpression:
        - - "\"input\".\"id\" = \"target\".\"id\""
          - "Case"
        whenMatched:
        - - "true"
          - "Update"
        updateMapping:
        - - "account_name"
          - "account_name"
        - - "annual_revenue"
          - "annual_revenue"
        - - "last_modified_timestamp"
          - "last_modified_timestamp"
        includeNotMatched: "Yes"
        insertMapping:
        - - "id"
          - "id"
        - - "account_name"
          - "account_name"
        - - "annual_revenue"
          - "annual_revenue"
        - - "last_modified_timestamp"
          - "last_modified_timestamp"
design:
  components:
    mtln_qs_sf_account:
      position:
        x: -190
        "y": -10
      tempMetlId: 1
    Rank:
      position:
        x: -60
        "y": -10
      tempMetlId: 2
    Filter:
      position:
        x: 60
        "y": -10
      tempMetlId: 3
    Rename:
      position:
        x: 190
        "y": -10
      tempMetlId: 4
    mtln_qs_sf_ods_account:
      position:
        x: 340
        "y": -10
      tempMetlId: 5
  notes:
    "1":
      position:
        x: -220
        "y": -230
      size:
        height: 190
        width: 610
      theme: "light-green"
      content: |-
        **Bronze** to **Silver** data transformations in the full load strategy.

        The job ensures there are no duplicates, and pushes the account data into the more generic operational data store (ODS) schema.

        The Table Update component runs a SQL `MERGE` operation. Note there is no need to be explicit about the surrogate key since it defaults to use the sequence.
