type: "transformation"
version: "1.0"
pipeline:
  components:
    stg_sample_reviews:
      type: "table-input"
      parameters:
        componentName: "stg_sample_reviews"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "stg_sample_reviews"
        columnNames:
        - "id"
        - "stars"
        - "product"
        - "review"
        timeOffset:
    stg_sample_reviews_genai:
      type: "table-input"
      parameters:
        componentName: "stg_sample_reviews_genai"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "stg_sample_reviews_genai"
        columnNames:
        - "id"
        - "DATA"
        timeOffset:
    Join:
      type: "join"
      sources:
      - "stg_sample_reviews"
      - "Extract Nested Data"
      parameters:
        componentName: "Join"
        mainTable: "stg_sample_reviews"
        mainTableAlias: "r"
        joins:
        - - "Extract Nested Data"
          - "ai"
          - "Left"
        joinExpressions:
        - - "\"ai\".\"id\" = \"r\".\"id\""
          - "r_Left_ai"
        columnMappings:
        - - "r.id"
          - "id"
        - - "r.stars"
          - "stars"
        - - "r.product"
          - "product"
        - - "r.review"
          - "review"
        - - "ai.ai_score"
          - "ai_score"
    Comparison:
      type: "calculator"
      sources:
      - "Join"
      parameters:
        componentName: "Comparison"
        includeInputColumns: "Yes"
        calculations:
        - - "ABS(\"stars\" - \"ai_score\")"
          - "difference"
    Extract Nested Data:
      type: "extract-nested-data-sf"
      sources:
      - "stg_sample_reviews_genai"
      parameters:
        componentName: "Extract Nested Data"
        includeInputColumns: "Yes"
        columns:
        - name: "ai_score"
          datatype: "NUMBER"
          size: "1"
          decimalPlaces: "0"
          columnName: "DATA"
          aliasName: "ai_score"
          isArray: "false"
          include: "true"
        outerJoin: "No"
        inputAlias: "i"
        arrayPrefix: "f"
        castingMethod: "Replace all unparseable values with null"
        caseColumnAliasNames: "No"
design:
  components:
    stg_sample_reviews:
      position:
        x: 150
        "y": 0
      tempMetlId: 1
    stg_sample_reviews_genai:
      position:
        x: 150
        "y": 130
      tempMetlId: 2
    Join:
      position:
        x: 460
        "y": 70
      tempMetlId: 4
    Comparison:
      position:
        x: 600
        "y": 70
      tempMetlId: 5
    Extract Nested Data:
      position:
        x: 300
        "y": 130
      tempMetlId: 6
  notes:
    "1":
      position:
        x: 350
        "y": -70
      size:
        height: 88
        width: 300
      theme: "white"
      content: "Compare the original star rating against the AI-generated rating"
