type: "transformation"
version: "1.0"
pipeline:
  components:
    mtln_qs_sf_case:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_case"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_case"
        timeOffset:
        columnNames:
        - "Id"
        - "CaseNumber"
        - "AccountId"
        - "ContactId"
        - "OwnerId"
        - "Status"
        - "CreatedDate"
        - "ClosedDate"
    mtln_qs_sf_account:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_account"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_account"
        timeOffset:
        columnNames:
        - "Id"
        - "Name"
        - "BillingCountry"
        - "BillingState"
    mtln_qs_sf_contact:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_contact"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_contact"
        timeOffset:
        columnNames:
        - "Id"
        - "Name"
    mtln_qs_sf_user:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_user"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_user"
        timeOffset:
        columnNames:
        - "Id"
        - "Name"
    Join:
      type: "join"
      sources:
      - "mtln_qs_sf_account"
      - "mtln_qs_sf_case"
      - "mtln_qs_sf_contact"
      - "mtln_qs_sf_user"
      parameters:
        componentName: "Join"
        mainTable: "mtln_qs_sf_case"
        mainTableAlias: "csa1"
        joins:
        - - "mtln_qs_sf_account"
          - "ccna2"
          - "Inner"
        - - "mtln_qs_sf_contact"
          - "cnta3"
          - "Left"
        - - "mtln_qs_sf_user"
          - "sra4"
          - "Left"
        joinExpressions:
        - - "\"csa1\".\"AccountId\" = \"ccna2\".\"Id\""
          - "csa1_Inner_ccna2"
        - - "\"csa1\".\"ContactId\" = \"cnta3\".\"Id\""
          - "csa1_Left_cnta3"
        - - "\"csa1\".\"OwnerId\" = \"sra4\".\"Id\""
          - "csa1_Left_sra4"
        columnMappings:
        - - "csa1.Id"
          - "csa1_Id"
        - - "csa1.CaseNumber"
          - "csa1_CaseNumber"
        - - "csa1.AccountId"
          - "csa1_AccountId"
        - - "csa1.ContactId"
          - "csa1_ContactId"
        - - "csa1.OwnerId"
          - "csa1_OwnerId"
        - - "csa1.Status"
          - "csa1_Status"
        - - "csa1.CreatedDate"
          - "csa1_CreatedDate"
        - - "csa1.ClosedDate"
          - "csa1_ClosedDate"
        - - "ccna2.Id"
          - "ccna2_Id"
        - - "ccna2.Name"
          - "ccna2_Name"
        - - "ccna2.BillingCountry"
          - "ccna2_BillingCountry"
        - - "ccna2.BillingState"
          - "ccna2_BillingState"
        - - "cnta3.Id"
          - "cnta3_Id"
        - - "cnta3.Name"
          - "cnta3_Name"
        - - "sra4.Id"
          - "sra4_Id"
        - - "sra4.Name"
          - "sra4_Name"
    Filter:
      type: "filter"
      sources:
      - "Join"
      parameters:
        componentName: "Filter"
        filterConditions:
        - - "csa1_Id"
          - "Not"
          - "Null or blank"
          - ""
        combineCondition: "And"
    Rewrite mtln_qs_sf_contacts_with_cases:
      type: "rewrite-table"
      sources:
      - "Filter"
      parameters:
        componentName: "Rewrite mtln_qs_sf_contacts_with_cases"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_contacts_with_cases"
        warehouse: "[Environment Default]"
        orderBy:
design:
  components:
    mtln_qs_sf_case:
      position:
        x: 0
        y: -150
      tempMetlId: 4
    mtln_qs_sf_account:
      position:
        x: 0
        y: -50
      tempMetlId: 5
    mtln_qs_sf_contact:
      position:
        x: 0
        y: 50
      tempMetlId: 6
    mtln_qs_sf_user:
      position:
        x: 0
        y: 150
      tempMetlId: 7
    Join:
      position:
        x: 150
        y: 0
      tempMetlId: 1
    Filter:
      position:
        x: 300
        y: 0
      tempMetlId: 2
    Rewrite mtln_qs_sf_contacts_with_cases:
      position:
        x: 450
        y: 0
      tempMetlId: 3
  notes:
    1:
      position:
        x: 200
        y: -130
      size:
        height: 200
        width: 240
      theme: "white"
      content: "Add your own filters here if you want to apply them before the integra\
        ted report is generated"
    2:
      position:
        x: -370
        y: -100
      size:
        height: 100
        width: 300
      theme: "white"
      content: "Add your own Table Inputs here to customize the integration with your \
        own data"
