type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Create raw_flights"
        - "Create airports"
        - "Create Table 3"
      parameters:
        componentName: "Start"
    Create raw_flights:
      type: "create-table"
      parameters:
        componentName: "Create raw_flights"
        createReplace: "Replace"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        newTableName: "raw_flights"
        tableType: "Permanent"
        columns:
        - - "year"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "month"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "dayofmonth"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "dayofweek"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "deptime"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "crsdeptime"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "arrtime"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "crsarrtime"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "uniquecarrier"
          - "VARCHAR"
          - "256"
          - ""
          - ""
          - "NO"
          - "NO"
          - ""
        - - "flightnum"
          - "VARCHAR"
          - "256"
          - ""
          - ""
          - "NO"
          - "NO"
          - ""
        - - "tailnum"
          - "VARCHAR"
          - "256"
          - ""
          - ""
          - "NO"
          - "NO"
          - ""
        - - "actualeslapsedtime"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "crselapsedtime"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "airtime"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "arrdelay"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "depdelay"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "origin"
          - "VARCHAR"
          - "256"
          - ""
          - ""
          - "NO"
          - "NO"
          - ""
        - - "dest"
          - "VARCHAR"
          - "256"
          - ""
          - ""
          - "NO"
          - "NO"
          - ""
        - - "distance"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "taxiin"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "taxiout"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "cancelled"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "cancellationcode"
          - "VARCHAR"
          - "256"
          - ""
          - ""
          - "NO"
          - "NO"
          - ""
        - - "diverted"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "carrierdelay"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "weatherdelay"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "nasdelay"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "securitydelay"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        - - "lateaircraftdelay"
          - "NUMBER"
          - "10"
          - "0"
          - ""
          - "NO"
          - "NO"
          - ""
        defaultDdlCollation:
        primaryKeys:
        clusteringKeys:
        dataRetentionTimeInDays:
        comment:
    Create airports:
      type: "create-table"
      parameters:
        componentName: "Create airports"
        createReplace: "Create if not exists"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        newTableName: "airports"
        tableType: "Permanent"
        columns:
        - - "airport_data"
          - "VARIANT"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - "No"
        defaultDdlCollation:
        primaryKeys:
        clusteringKeys:
        dataRetentionTimeInDays:
        comment:
    Create Table 3:
      type: "create-table"
      parameters:
        componentName: "Create Table 3"
        createReplace: "Create if not exists"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        newTableName:
        tableType: "Permanent"
        columns:
        defaultDdlCollation:
        primaryKeys:
        clusteringKeys:
        dataRetentionTimeInDays:
        comment:
design:
  components:
    Start:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    Create raw_flights:
      position:
        x: 180
        "y": -130
      tempMetlId: 2
    Create airports:
      position:
        x: 180
        "y": 0
      tempMetlId: 3
    Create Table 3:
      position:
        x: 180
        "y": 120
      tempMetlId: 4
