type: "transformation"
version: "1.0"
pipeline:
  components:
    Join:
      type: "join"
      sources:
      - "mtln_qs_sf_account"
      - "mtln_qs_sf_opportunity"
      - "mtln_qs_sf_user"
      parameters:
        componentName: "Join"
        mainTable: "mtln_qs_sf_account"
        mainTableAlias: "ccna1"
        joins:
        - - "mtln_qs_sf_user"
          - "sra2"
          - "Left"
        - - "mtln_qs_sf_opportunity"
          - "ppra3"
          - "Inner"
        joinExpressions:
        - - "\"ccna1\".\"OwnerId\" = \"sra2\".\"Id\""
          - "ccna1_Left_sra2"
        - - "\"ccna1\".\"Id\" = \"ppra3\".\"AccountId\""
          - "ccna1_Inner_ppra3"
        columnMappings:
        - - "ccna1.Id"
          - "ccna1_Id"
        - - "ccna1.Name"
          - "ccna1_Name"
        - - "ccna1.OwnerId"
          - "ccna1_OwnerId"
        - - "ccna1.BillingCountry"
          - "ccna1_BillingCountry"
        - - "ccna1.BillingState"
          - "ccna1_BillingState"
        - - "sra2.Id"
          - "sra2_Id"
        - - "sra2.Name"
          - "sra2_Name"
        - - "ppra3.Id"
          - "ppra3_Id"
        - - "ppra3.AccountId"
          - "ppra3_AccountId"
        - - "ppra3.Name"
          - "ppra3_Name"
        - - "ppra3.CreatedDate"
          - "ppra3_CreatedDate"
    Filter:
      type: "filter"
      sources:
      - "Rank Descending"
      parameters:
        componentName: "Filter"
        filterConditions:
        - - "ccna1_Id"
          - "Not"
          - "Null or blank"
          - ""
        - - "rn"
          - "Is"
          - "Equal to"
          - "1"
        combineCondition: "And"
    Rewrite mtln_qs_sf_account_first_opportunity:
      type: "rewrite-table"
      sources:
      - "Rename"
      parameters:
        componentName: "Rewrite mtln_qs_sf_account_first_opportunity"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_account_first_opportunity"
        orderBy:
    mtln_qs_sf_account:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_account"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_account"
        columnNames:
        - "Id"
        - "Name"
        - "OwnerId"
        - "BillingCountry"
        - "BillingState"
        timeOffset:
    mtln_qs_sf_user:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_user"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_user"
        columnNames:
        - "Id"
        - "Name"
        timeOffset:
    mtln_qs_sf_opportunity:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_opportunity"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_opportunity"
        columnNames:
        - "Id"
        - "AccountId"
        - "Name"
        - "CreatedDate"
        timeOffset:
    Rank Descending:
      type: "rank"
      sources:
      - "Join"
      parameters:
        componentName: "Rank Descending"
        includeInputColumns: "Yes"
        partitionData:
        - "ccna1_Id"
        orderingWithinPartitions:
        - - "ppra3_CreatedDate"
          - "Descending"
        functions:
        - - "Row Number"
          - "rn"
    Rename:
      type: "rename"
      sources:
      - "Filter"
      parameters:
        componentName: "Rename"
        columnMapping:
        - - "ccna1_Id"
          - "ccna1_Id"
        - - "ccna1_Name"
          - "ccna1_Name"
        - - "ccna1_OwnerId"
          - "ccna1_OwnerId"
        - - "ccna1_BillingCountry"
          - "ccna1_BillingCountry"
        - - "ccna1_BillingState"
          - "ccna1_BillingState"
        - - "sra2_Id"
          - "sra2_Id"
        - - "sra2_Name"
          - "sra2_Name"
        - - "ppra3_Id"
          - "ppra3_Id"
        - - "ppra3_AccountId"
          - "ppra3_AccountId"
        - - "ppra3_Name"
          - "ppra3_Name"
        - - "ppra3_CreatedDate"
          - "ppra3_CreatedDate"
        includeInputColumns: "No"
design:
  components:
    Join:
      position:
        x: 150
        "y": 0
      tempMetlId: 1
    Filter:
      position:
        x: 450
        "y": 0
      tempMetlId: 2
    Rewrite mtln_qs_sf_account_first_opportunity:
      position:
        x: 760
        "y": 0
      tempMetlId: 3
    mtln_qs_sf_account:
      position:
        x: 0
        "y": -100
      tempMetlId: 4
    mtln_qs_sf_user:
      position:
        x: 0
        "y": 0
      tempMetlId: 5
    mtln_qs_sf_opportunity:
      position:
        x: 0
        "y": 100
      tempMetlId: 6
    Rank Descending:
      position:
        x: 300
        "y": 0
      tempMetlId: 7
    Rename:
      position:
        x: 610
        "y": 0
      tempMetlId: 8
  notes:
    "1":
      position:
        x: 350
        "y": -130
      size:
        height: 210
        width: 240
      theme: "white"
      content: "Add your own filters here if you want to apply them before the integrated\
        \ report is generated"
    "2":
      position:
        x: -370
        "y": -100
      size:
        height: 110
        width: 300
      theme: "white"
      content: "Add your own Table Inputs here to customize the integration with your\
        \ own data"
