type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Salesforce Task"
        - "Salesforce Event"
        - "Salesforce RecordType"
      parameters:
        componentName: "Start"
    Sync:
      type: "and"
      transitions:
        unconditional:
        - "Run qs-sf-unite-task-and-event-tran"
      parameters:
        componentName: "Sync"
    Salesforce Task:
      type: "salesforce-query"
      transitions:
        success:
        - "Sync"
      parameters:
        componentName: "Salesforce Task"
        basicAdvancedMode: "Basic"
        authenticationMethod: "OAuth"
        useSandbox: "No"
        authentication: "${SalesforceOAuthName}"
        connectionOptions:
        dataSource: "Task"
        dataSelection:
        - "Id"
        - "AccountId"
        - "ActivityDate"
        - "CreatedById"
        - "CreatedDate"
        - "CurrencyIsoCode"
        - "Description"
        - "IsArchived"
        - "IsDeleted"
        - "IsRecurrence"
        - "IsReminderSet"
        - "LastModifiedById"
        - "LastModifiedDate"
        - "OwnerId"
        - "RecordTypeId"
        - "RecurrenceActivityId"
        - "RecurrenceDayOfMonth"
        - "RecurrenceDayOfWeekMask"
        - "RecurrenceEndDateOnly"
        - "RecurrenceInstance"
        - "RecurrenceInterval"
        - "RecurrenceMonthOfYear"
        - "RecurrenceTimeZoneSidKey"
        - "RecurrenceType"
        - "ReminderDateTime"
        - "Subject"
        - "SystemModstamp"
        - "Type"
        - "WhatCount"
        - "WhatId"
        - "WhoCount"
        - "WhoId"
        dataSourceFilter:
        combineFilters: "And"
        limit: ""
        type: "Standard"
        primaryKeys:
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_task"
        stage: "[Custom]"
        stagePlatform: "Snowflake Managed"
        loadOptions:
        autoDebug: "Off"
    Salesforce Event:
      type: "salesforce-query"
      transitions:
        success:
        - "Sync"
      parameters:
        componentName: "Salesforce Event"
        basicAdvancedMode: "Basic"
        authenticationMethod: "OAuth"
        useSandbox: "No"
        authentication: "${SalesforceOAuthName}"
        connectionOptions:
        dataSource: "Event"
        dataSelection:
        - "Id"
        - "AccountId"
        - "ActivityDate"
        - "CreatedById"
        - "CreatedDate"
        - "CurrencyIsoCode"
        - "Description"
        - "IsArchived"
        - "IsDeleted"
        - "IsRecurrence"
        - "IsReminderSet"
        - "LastModifiedById"
        - "LastModifiedDate"
        - "OwnerId"
        - "RecordTypeId"
        - "RecurrenceActivityId"
        - "RecurrenceDayOfMonth"
        - "RecurrenceDayOfWeekMask"
        - "RecurrenceEndDateOnly"
        - "RecurrenceInstance"
        - "RecurrenceInterval"
        - "RecurrenceMonthOfYear"
        - "RecurrenceTimeZoneSidKey"
        - "RecurrenceType"
        - "ReminderDateTime"
        - "Subject"
        - "SystemModstamp"
        - "Type"
        - "WhatCount"
        - "WhatId"
        - "WhoCount"
        - "WhoId"
        dataSourceFilter:
        combineFilters: "And"
        limit: ""
        type: "Standard"
        primaryKeys:
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_event"
        stage: "[Custom]"
        stagePlatform: "Snowflake Managed"
        loadOptions:
        autoDebug: "Off"
    Salesforce RecordType:
      type: "salesforce-query"
      transitions:
        success:
        - "Sync"
      parameters:
        componentName: "Salesforce RecordType"
        basicAdvancedMode: "Basic"
        authenticationMethod: "OAuth"
        useSandbox: "No"
        authentication: "${SalesforceOAuthName}"
        connectionOptions:
        dataSource: "RecordType"
        dataSelection:
        - "Id"
        - "Name"
        dataSourceFilter:
        combineFilters: "And"
        limit: ""
        type: "Standard"
        primaryKeys:
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_record_type"
        stage: "[Custom]"
        stagePlatform: "Snowflake Managed"
        loadOptions:
        autoDebug: "Off"
    Run qs-sf-unite-task-and-event-tran:
      type: "run-transformation"
      parameters:
        componentName: "Run qs-sf-unite-task-and-event-tran"
        transformationJob: "qs-sf-unite-task-and-event-tran"
        setScalarVariables:
        setGridVariables:
  variables:
    SalesforceOAuthName:
      metadata:
        type: "TEXT"
        description: "Name of your Salesforce OAuth"
        scope: "COPIED"
        visibility: "PRIVATE"
      defaultValue: "Your-Salesforce-OAuth-name"
design:
  components:
    Start:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    Sync:
      position:
        x: 300
        "y": 0
      tempMetlId: 2
    Salesforce Task:
      position:
        x: 150
        "y": -100
      tempMetlId: 4
    Salesforce Event:
      position:
        x: 150
        "y": 0
      tempMetlId: 5
    Salesforce RecordType:
      position:
        x: 150
        "y": 100
      tempMetlId: 6
    Run qs-sf-unite-task-and-event-tran:
      position:
        x: 460
        "y": 0
      tempMetlId: 7
  notes:
    "1":
      position:
        x: -300
        "y": -110
      size:
        height: 130
        width: 270
      theme: "light-red"
      content: "Please set the default value of the `SalesforceOAuthName` pipeline\
        \ variable before running or validating"
