type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Run Data Vault Quickstart - Create Sample Data"
      parameters:
        componentName: "Start"
    Run Data Vault Quickstart - Create Sample Data:
      type: "run-transformation"
      transitions:
        success:
        - "Stage to Hub - equipment"
        - "Stage to Hub - bubble_event"
      parameters:
        componentName: "Run Data Vault Quickstart - Create Sample Data"
        transformationJob: "Data Vault Quickstart - Create Sample Data"
        setScalarVariables:
        setGridVariables:
    Stage to Hub - equipment:
      type: "run-orchestration"
      transitions:
        success:
        - "And"
      parameters:
        componentName: "Stage to Hub - equipment"
        orchestrationJob: "Data Vault Quickstart - Stage to Hub"
        setScalarVariables:
        - - "jv_database"
          - "NAME_OF_YOUR_DATABASE"
        - - "jv_schema"
          - "YOUR_SCHEMA"
        - - "jv_table_name_stub"
          - "equipment"
        - - "jv_record_source"
          - "Operations"
        - - "jv_staging_view_name"
          - "v_hub_equipment_source"
        setGridVariables:
        - variable: "gv_business_key"
          status: "values"
          gridValues:
          - - "equipment_id"
    Stage to Hub - bubble_event:
      type: "run-orchestration"
      transitions:
        success:
        - "And"
      parameters:
        componentName: "Stage to Hub - bubble_event"
        orchestrationJob: "Data Vault Quickstart - Stage to Hub"
        setScalarVariables:
        - - "jv_database"
          - "NAME_OF_YOUR_DATABASE"
        - - "jv_schema"
          - "YOUR_SCHEMA"
        - - "jv_table_name_stub"
          - "bubble_event"
        - - "jv_record_source"
          - "Operations"
        - - "jv_staging_view_name"
          - "v_bubble_event_source"
        setGridVariables:
        - variable: "gv_business_key"
          status: "values"
          gridValues:
          - - "ts"
          - - "equipment_alias"
    Stage to Link:
      type: "run-orchestration"
      parameters:
        componentName: "Stage to Link"
        orchestrationJob: "Data Vault Quickstart - Stage to Link"
        setScalarVariables:
        - - "jv_database"
          - "NAME_OF_YOUR_DATABASE"
        - - "jv_schema"
          - "YOUR_SCHEMA"
        - - "jv_link_suffix"
          - "link"
        - - "jv_record_source"
          - "Operations"
        - - "jv_staging_view_name"
          - "v_bubble_event_equipment_link"
        setGridVariables:
        - variable: "gv_hubs_to_link"
          status: "values"
          gridValues:
          - - "equipment"
          - - "bubble_event"
    And:
      type: "and"
      transitions:
        unconditional:
        - "Stage to Link"
      parameters:
        componentName: "And"
design:
  components:
    Start:
      position:
        x: 50
        "y": -60
      tempMetlId: 1
    Run Data Vault Quickstart - Create Sample Data:
      position:
        x: 170
        "y": -60
      tempMetlId: 2
    Stage to Hub - equipment:
      position:
        x: 330
        "y": -120
      tempMetlId: 4
    Stage to Hub - bubble_event:
      position:
        x: 330
        "y": 0
      tempMetlId: 5
    Stage to Link:
      position:
        x: 610
        "y": -60
      tempMetlId: 6
    And:
      position:
        x: 480
        "y": -60
      tempMetlId: 7
  notes:
    "1":
      position:
        x: 20
        "y": -240
      size:
        height: 98
        width: 670
      theme: "white"
      content: |-
        Run this to create the Data Vault objects from the quickstart data.

        Before running, you must adjust the database and schema names to your own values.
