type: "transformation"
version: "1.0"
pipeline:
  components:
    mtln_qs_sf_opportunity:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_opportunity"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_opportunity"
        timeOffset:
        columnNames:
        - "Id"
        - "AccountId"
        - "OwnerId"
        - "CampaignId"
        - "Name"
    mtln_qs_sf_account:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_account"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_account"
        timeOffset:
        columnNames:
        - "Id"
        - "Name"
        - "OwnerId"
        - "BillingCountry"
        - "BillingState"
    mtln_qs_sf_user:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_user"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_user"
        timeOffset:
        columnNames:
        - "Id"
        - "Name"
    mtln_qs_sf_campaign:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_campaign"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_campaign"
        timeOffset:
        columnNames:
        - "Id"
        - "Name"
    Join:
      type: "join"
      sources:
      - "mtln_qs_sf_account"
      - "mtln_qs_sf_campaign"
      - "mtln_qs_sf_opportunity"
      - "mtln_qs_sf_user"
      parameters:
        componentName: "Join"
        mainTable: "mtln_qs_sf_opportunity"
        mainTableAlias: "ppra1"
        joins:
        - - "mtln_qs_sf_account"
          - "ccna2"
          - "Inner"
        - - "mtln_qs_sf_user"
          - "sra3"
          - "Inner"
        - - "mtln_qs_sf_campaign"
          - "cmpa4"
          - "Left"
        joinExpressions:
        - - "\"ppra1\".\"AccountId\" = \"ccna2\".\"Id\""
          - "ppra1_Inner_ccna2"
        - - "\"ppra1\".\"OwnerId\" = \"sra3\".\"Id\""
          - "ppra1_Inner_sra3"
        - - "\"ppra1\".\"CampaignId\" = \"cmpa4\".\"Id\""
          - "ppra1_Left_cmpa4"
        columnMappings:
        - - "ppra1.Id"
          - "ppra1_Id"
        - - "ppra1.AccountId"
          - "ppra1_AccountId"
        - - "ppra1.OwnerId"
          - "ppra1_OwnerId"
        - - "ppra1.CampaignId"
          - "ppra1_CampaignId"
        - - "ppra1.Name"
          - "ppra1_Name"
        - - "ccna2.Id"
          - "ccna2_Id"
        - - "ccna2.Name"
          - "ccna2_Name"
        - - "ccna2.OwnerId"
          - "ccna2_OwnerId"
        - - "ccna2.BillingCountry"
          - "ccna2_BillingCountry"
        - - "ccna2.BillingState"
          - "ccna2_BillingState"
        - - "sra3.Id"
          - "sra3_Id"
        - - "sra3.Name"
          - "sra3_Name"
        - - "cmpa4.Id"
          - "cmpa4_Id"
        - - "cmpa4.Name"
          - "cmpa4_Name"
    Filter:
      type: "filter"
      sources:
      - "Join"
      parameters:
        componentName: "Filter"
        filterConditions:
        - - "ppra1_Id"
          - "Not"
          - "Null or blank"
          - ""
        combineCondition: "And"
    Rewrite mtln_qs_sf_opportunities_with_primary_campaign_source:
      type: "rewrite-table"
      sources:
      - "Filter"
      parameters:
        componentName: "Rewrite mtln_qs_sf_opportunities_with_primary_campaign_source"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_opportunities_with_primary_campaign_source"
        warehouse: "[Environment Default]"
        orderBy:
design:
  components:
    mtln_qs_sf_opportunity:
      position:
        x: 0
        y: -150
      tempMetlId: 4
    mtln_qs_sf_account:
      position:
        x: 0
        y: -50
      tempMetlId: 5
    mtln_qs_sf_user:
      position:
        x: 0
        y: 50
      tempMetlId: 6
    mtln_qs_sf_campaign:
      position:
        x: 0
        y: 150
      tempMetlId: 7
    Join:
      position:
        x: 150
        y: 0
      tempMetlId: 1
    Filter:
      position:
        x: 300
        y: 0
      tempMetlId: 2
    Rewrite mtln_qs_sf_opportunities_with_primary_campaign_source:
      position:
        x: 450
        y: 0
      tempMetlId: 3
  notes:
    1:
      position:
        x: 200
        y: -130
      size:
        height: 200
        width: 240
      theme: "white"
      content: "Add your own filters here if you want to apply them before the integra\
        ted report is generated"
    2:
      position:
        x: -370
        y: -100
      size:
        height: 100
        width: 300
      theme: "white"
      content: "Add your own Table Inputs here to customize the integration with your \
        own data"
