type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "OpenAI Prompt"
      parameters:
        componentName: "Start"
    OpenAI Prompt:
      type: "openai-ai-prompt"
      parameters:
        componentName: "OpenAI Prompt"
        openAI:
          model: "gpt-3.5-turbo"
          apiKey: "OpenAI-Key"
          temperature: "1"
          topP: "1"
          "n": "1"
          maxTokens:
        source:
          snowflake:
            database: "[Environment Default]"
            schema: "[Environment Default]"
            table: "top_10_athletes_summer_2016"
            keyColumn: "Name"
            limit: "1000"
        promptContext:
          userContext: "You are a reporter on athletic events. Write a short bio on\
            \ how the named athlete performed in the Summer 2016 Olympic Games"
          inputs:
          - - "Name"
            - "Athlete"
            - "Text"
          outputFormat: "TEXT"
        destination:
          snowflake:
            database: "[Environment Default]"
            schema: "[Environment Default]"
            table: "top_10_athletes_summer_2016_OpenAI"
            createTableOptions: "Replace if Table Exists"
        ragConfig:
          isRagEnabled: "No"
design:
  components:
    Start:
      position:
        x: -20
        "y": 0
      tempMetlId: 1
    OpenAI Prompt:
      position:
        x: 140
        "y": 0
      tempMetlId: 2
  notes:
    "1":
      position:
        x: 60
        "y": -250
      size:
        height: 380
        width: 340
      theme: "white"
      content: "The **OpenAI Prompt** component uses the OpenAI API to query a GPT-3\
        \ model with a prompt based on data from the \"top_10_athletes_summer_2016\"\
        \ table in Snowflake. It sends the \"Name\" column value as the prompt context\
        \ and sets the output format to text. The response from the model is written\
        \ back to the \"top_10_athletes_summer_2016_OpenAI\" table in Snowflake."
