type: "orchestration"
version: "1.0"
pipeline:
  components:
    Size Up Warehouse:
      type: "alter-warehouse"
      transitions:
        unconditional:
        - "Grid Iterator 0"
      parameters:
        componentName: "Size Up Warehouse"
        warehouse: "[Environment Default]"
        commandType: "Set"
        properties:
        - - "WAREHOUSE_SIZE"
          - "XLARGE"
    Size Down Warehouse:
      type: "alter-warehouse"
      transitions:
        unconditional:
        - "Webhook Post 0"
      parameters:
        componentName: "Size Down Warehouse"
        warehouse: "[Environment Default]"
        commandType: "Set"
        properties:
        - - "WAREHOUSE_SIZE"
          - "XSMALL"
    Extract Odds Data:
      type: "unknown-orchestration"
      parameters:
        "1": "Extract Odds Data"
        "2": "CollegeFootballData"
        "3": "Production"
        "4": "default"
        "5": "BettingLines"
        "6":
        "7": ""
        "8": ""
        "9": ""
        "10": ""
        "11": "4"
        "12":
        "13":
          "1":
          - - "year"
            - "${jv_year}"
        "14":
          "1":
          - - "Authorization"
            - "Bearer pQJWHv3l90s2Np4GFXx/vcvDiePoMzbDT79DYck0zsfWgK8auGkczIXJhNZYoVF8"
        "15": ""
        "16": ""
        "17": ""
        "18": ""
        "22": "CollegeFootballData"
        "113": "s3://mtln-kareyg/CFB_API/"
        "114": "[Environment Default]"
        "115": "[Environment Default]"
        "116": "[Environment Default]"
        "117": "Odds_${jv_year}"
        "118": ""
    Start 0:
      type: "start"
      transitions:
        unconditional:
        - "Size Up Warehouse"
      parameters:
        componentName: "Start 0"
    v2_1hr_xform1 0:
      type: "run-transformation"
      transitions:
        unconditional:
        - "Size Down Warehouse"
      parameters:
        componentName: "v2_1hr_xform1 0"
        transformationJob: "deleteme/Tech Workshops/v2_1hr/v2_1hr_xform1"
        setScalarVariables:
        setGridVariables:
    Grid Iterator 0:
      type: "grid-iterator"
      transitions:
        unconditional:
        - "v2_1hr_xform1 0"
      iterationTarget: "Extract Odds Data"
      parameters:
        componentName: "Grid Iterator 0"
        gridVariable: "years"
        gridIteratorVariableMapping:
        - - "year"
          - "jv_year"
        breakOnFailure: "No"
        concurrency: "Sequential"
    Webhook Post 0:
      type: "webhook-post"
      parameters:
        componentName: "Webhook Post 0"
        incomingWebhookUrl: "https://hooks.slack.com/services/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"
        payloadTemplate: "[Custom]"
        payload: "{'text':'Great job or whatever'}"
  variables:
    api_load_duration:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_year:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "default"
    CFB_grid:
      metadata:
        type: "GRID"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
        columns:
          gv_profile_name:
            columnType: "TEXT"
          gv_year:
            columnType: "TEXT"
      defaultValue: []
    years:
      metadata:
        type: "GRID"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
        columns:
          year:
            columnType: "TEXT"
      defaultValue:
      - - "2017"
      - - "2018"
      - - "2019"
      - - "2020"
      - - "2021"
design:
  components:
    Size Up Warehouse:
      position:
        x: -544
        "y": -16
      tempMetlId: 71502
    Size Down Warehouse:
      position:
        x: 0
        "y": -16
      tempMetlId: 71503
    Extract Odds Data:
      position:
        x: -352
        "y": 16
      tempMetlId: 71504
    Start 0:
      position:
        x: -688
        "y": -16
      tempMetlId: 71505
    v2_1hr_xform1 0:
      position:
        x: -160
        "y": -16
      tempMetlId: 71506
    Grid Iterator 0:
      position:
        x: -352
        "y": -16
      tempMetlId: 71507
    Webhook Post 0:
      position:
        x: 144
        "y": -16
      tempMetlId: 71509
  notes:
    "71501":
      position:
        x: -704
        "y": -172
      size:
        height: 119
        width: 586
      theme: "green"
      content: |-
        **WHAT ARE WE TRYING TO SOLVE?**:
        Find the biggest "upset" of the past five seasons of college football

        upset (n) - an unexpected result or situation, especially in a sports competition

        **HOW WE WILL SOLVE OUR BUSINESS PROBLEM**
        Pull in betting data from API (predicted results) and compare to game scores (actual results)
