type: "transformation"
version: "1.0"
pipeline:
  components:
    stg_aws_rss_feed:
      type: "table-input"
      parameters:
        componentName: "stg_aws_rss_feed"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "stg_aws_rss_feed"
        columnNames:
        - "channel"
        timeOffset:
    Flatten XML:
      type: "sql"
      sources:
      - "stg_aws_rss_feed"
      parameters:
        componentName: "Flatten XML"
        query: "SELECT XMLGET(VALUE, 'guid', 0):\"$\"::string AS guid,\r\n       XMLGET(VALUE,\
          \ 'title', 0):\"$\"::string AS title,\r\n       XMLGET(VALUE, 'description',\
          \ 0):\"$\"::string AS description,\r\n       XMLGET(VALUE, 'pubDate', 0):\"\
          $\"::date AS pubDate\r\nFROM $T{stg_aws_rss_feed} \"f\",\r\n     LATERAL\
          \ FLATTEN(to_array(\"f\".\"channel\":\"$\" )) xml_doc\r\nWHERE VALUE LIKE\
          \ '<item>%'"
    aws_rss_feed:
      type: "table-update"
      sources:
      - "Flatten XML"
      parameters:
        componentName: "aws_rss_feed"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "aws_rss_feed"
        targetAlias: "target"
        sourceAlias: "input"
        joinExpression:
        - - "\"input\".\"GUID\" = \"target\".\"GUID\""
          - "Case"
        whenMatched:
        - - "true"
          - "Update"
        updateMapping:
        - - "TITLE"
          - "TITLE"
        - - "DESCRIPTION"
          - "DESCRIPTION"
        - - "PUBDATE"
          - "PUBDATE"
        includeNotMatched: "Yes"
        insertMapping:
        - - "GUID"
          - "GUID"
        - - "TITLE"
          - "TITLE"
        - - "DESCRIPTION"
          - "DESCRIPTION"
        - - "PUBDATE"
          - "PUBDATE"
design:
  components:
    stg_aws_rss_feed:
      position:
        x: -30
        "y": 0
      tempMetlId: 1
    Flatten XML:
      position:
        x: 130
        "y": 0
      tempMetlId: 2
    aws_rss_feed:
      position:
        x: 280
        "y": 0
      tempMetlId: 3
  notes:
    "1":
      position:
        x: 40
        "y": -120
      size:
        height: 98
        width: 350
      theme: "light-green"
      content: "Flatten all the <item>s from the RSS feed, and merge them into the\
        \ permanent target table"
