type: "transformation"
version: "1.0"
pipeline:
  components:
    Join:
      type: "join"
      sources:
      - "mtln_qs_sf_account"
      - "mtln_qs_sf_campaign"
      - "mtln_qs_sf_campaignmember"
      - "mtln_qs_sf_contact"
      - "mtln_qs_sf_lead"
      parameters:
        componentName: "Join"
        mainTable: "mtln_qs_sf_campaignmember"
        mainTableAlias: "cmpa1"
        joins:
        - - "mtln_qs_sf_campaign"
          - "cmpa2"
          - "Inner"
        - - "mtln_qs_sf_contact"
          - "cnta3"
          - "Left"
        - - "mtln_qs_sf_lead"
          - "lda4"
          - "Left"
        - - "mtln_qs_sf_account"
          - "ccna5"
          - "Left"
        joinExpressions:
        - - "\"cmpa1\".\"CampaignId\" = \"cmpa2\".\"Id\""
          - "cmpa1_Inner_cmpa2"
        - - "\"cmpa1\".\"Type\" = 'Contact' AND \"cmpa1\".\"ContactId\" = \"cnta3\"\
            .\"Id\""
          - "cmpa1_Left_cnta3"
        - - "\"cmpa1\".\"Type\" = 'Lead' AND \"cmpa1\".\"LeadId\" = \"lda4\".\"Id\""
          - "cmpa1_Left_lda4"
        - - "\"cnta3\".\"AccountId\" = \"ccna5\".\"Id\"\r\nOR \"lda4\".\"ConvertedAccountId\"\
            \ = \"ccna5\".\"Id\""
          - "cmpa1_Left_ccna5"
        columnMappings:
        - - "cmpa1.Id"
          - "cmpa1_Id"
        - - "cmpa1.CampaignId"
          - "cmpa1_CampaignId"
        - - "cmpa1.ContactId"
          - "cmpa1_ContactId"
        - - "cmpa1.LeadId"
          - "cmpa1_LeadId"
        - - "cmpa1.LeadOrContactId"
          - "cmpa1_LeadOrContactId"
        - - "cmpa1.Status"
          - "cmpa1_Status"
        - - "cmpa1.Type"
          - "cmpa1_Type"
        - - "cmpa1.CreatedDate"
          - "cmpa1_CreatedDate"
        - - "cmpa1.LastModifiedDate"
          - "cmpa1_LastModifiedDate"
        - - "cmpa1.Name"
          - "cmpa1_Name"
        - - "cmpa1.Description"
          - "cmpa1_Description"
        - - "cmpa2.Id"
          - "cmpa2_Id"
        - - "cmpa2.CreatedDate"
          - "cmpa2_CreatedDate"
        - - "cmpa2.LastModifiedDate"
          - "cmpa2_LastModifiedDate"
        - - "cmpa2.Name"
          - "cmpa2_Name"
        - - "cmpa2.Description"
          - "cmpa2_Description"
        - - "cmpa2.StartDate"
          - "cmpa2_StartDate"
        - - "cmpa2.EndDate"
          - "cmpa2_EndDate"
        - - "cmpa2.Status"
          - "cmpa2_Status"
        - - "cmpa2.Type"
          - "cmpa2_Type"
        - - "cnta3.Id"
          - "cnta3_Id"
        - - "cnta3.Name"
          - "cnta3_Name"
        - - "cnta3.AccountId"
          - "cnta3_AccountId"
        - - "lda4.Id"
          - "lda4_Id"
        - - "lda4.Name"
          - "lda4_Name"
        - - "lda4.ConvertedDate"
          - "lda4_ConvertedDate"
        - - "lda4.ConvertedContactId"
          - "lda4_ConvertedContactId"
        - - "lda4.ConvertedAccountId"
          - "lda4_ConvertedAccountId"
        - - "ccna5.Id"
          - "ccna5_Id"
        - - "ccna5.Name"
          - "ccna5_Name"
        - - "ccna5.BillingCountry"
          - "ccna5_BillingCountry"
        - - "ccna5.BillingState"
          - "ccna5_BillingState"
        - - "ccna5.OwnerId"
          - "ccna5_OwnerId"
    Filter:
      type: "filter"
      sources:
      - "Join"
      parameters:
        componentName: "Filter"
        filterConditions:
        - - "cmpa1_Id"
          - "Not"
          - "Null or blank"
          - ""
        combineCondition: "And"
    Rewrite mtln_qs_sf_campaigns_with_contacts_or_leads:
      type: "rewrite-table"
      sources:
      - "Filter"
      parameters:
        componentName: "Rewrite mtln_qs_sf_campaigns_with_contacts_or_leads"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_campaigns_with_contacts_or_leads"
        orderBy:
    mtln_qs_sf_campaignmember:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_campaignmember"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_campaignmember"
        columnNames:
        - "Id"
        - "CampaignId"
        - "ContactId"
        - "LeadId"
        - "LeadOrContactId"
        - "Status"
        - "Type"
        - "CreatedDate"
        - "LastModifiedDate"
        - "Name"
        - "Description"
        timeOffset:
    mtln_qs_sf_campaign:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_campaign"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_campaign"
        columnNames:
        - "Id"
        - "CreatedDate"
        - "LastModifiedDate"
        - "Name"
        - "Description"
        - "StartDate"
        - "EndDate"
        - "Status"
        - "Type"
        timeOffset:
    mtln_qs_sf_contact:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_contact"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_contact"
        columnNames:
        - "Id"
        - "Name"
        - "AccountId"
        timeOffset:
    mtln_qs_sf_lead:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_lead"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_lead"
        columnNames:
        - "Id"
        - "Name"
        - "ConvertedDate"
        - "ConvertedContactId"
        - "ConvertedAccountId"
        timeOffset:
    mtln_qs_sf_account:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_account"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_account"
        columnNames:
        - "Id"
        - "Name"
        - "BillingCountry"
        - "BillingState"
        - "OwnerId"
        timeOffset:
design:
  components:
    Join:
      position:
        x: 150
        "y": 0
      tempMetlId: 1
    Filter:
      position:
        x: 300
        "y": 0
      tempMetlId: 2
    Rewrite mtln_qs_sf_campaigns_with_contacts_or_leads:
      position:
        x: 450
        "y": 0
      tempMetlId: 3
    mtln_qs_sf_campaignmember:
      position:
        x: 0
        "y": -200
      tempMetlId: 4
    mtln_qs_sf_campaign:
      position:
        x: 0
        "y": -100
      tempMetlId: 5
    mtln_qs_sf_contact:
      position:
        x: 0
        "y": 0
      tempMetlId: 6
    mtln_qs_sf_lead:
      position:
        x: 0
        "y": 100
      tempMetlId: 7
    mtln_qs_sf_account:
      position:
        x: 0
        "y": 200
      tempMetlId: 8
  notes:
    "1":
      position:
        x: 200
        "y": -130
      size:
        height: 200
        width: 240
      theme: "white"
      content: "Add your own filters here if you want to apply them before the integrated\
        \ report is generated"
    "2":
      position:
        x: -370
        "y": -100
      size:
        height: 110
        width: 300
      theme: "white"
      content: "Add your own Table Inputs here to customize the integration with your\
        \ own data"
