type: "transformation"
version: "1.0"
pipeline:
  components:
    BettingOdds:
      type: "table-input"
      parameters:
        componentName: "BettingOdds"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "BettingOdds"
        columnNames:
        - "Data Value"
        timeOffset: ""
    Rank 0:
      type: "rank"
      sources:
      - "Extract Nested Data 0"
      parameters:
        componentName: "Rank 0"
        includeInputColumns: "Yes"
        partitionData:
        - "awayTeam"
        - "homeTeam"
        orderingWithinPartitions:
        - - "awayTeam"
          - "Asc"
        - - "homeTeam"
          - "Asc"
        functions:
        - - "Row Number"
          - "rn"
    Calculator 0:
      type: "calculator"
      sources:
      - "Filter 0"
      parameters:
        componentName: "Calculator 0"
        includeInputColumns: "Yes"
        calculations:
        - - "regexp_replace(\"formattedSpread\",'-.*','')"
          - "projectedWinner"
        - - "IFNULL(LTRIM(\"spread\",'- '),0)"
          - "spread"
        - - "CASE WHEN \"homeScore\" < \"awayScore\" THEN \"awayTeam\" ELSE \"homeTeam\"\
            \ END"
          - "actualWinner"
        - - "ABS(\"awayScore\"-\"homeScore\")"
          - "scoreDifference"
    Extract Nested Data 0:
      type: "extract-nested-data-sf"
      sources:
      - "BettingOdds"
      parameters:
        componentName: "Extract Nested Data 0"
        includeInputColumns: "No"
        columns:
        - name: "awayConference"
          datatype: "VARIANT"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "awayConference"
          isArray: "false"
          include: "false"
        - name: "awayScore"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "awayScore"
          isArray: "false"
          include: "true"
        - name: "awayTeam"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "awayTeam"
          isArray: "false"
          include: "true"
        - name: "homeConference"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "homeConference"
          isArray: "false"
          include: "false"
        - name: "homeScore"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "homeScore"
          isArray: "false"
          include: "true"
        - name: "homeTeam"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "homeTeam"
          isArray: "false"
          include: "true"
        - name: "lines"
          datatype: "VARIANT"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "lines"
          isArray: "true"
          include: "false"
          childElements:
          - name: "lines-element"
            datatype: "VARIANT"
            size: "0"
            decimalPlaces: "0"
            columnName: "Data Value"
            aliasName: "lines-element"
            isArray: "false"
            include: "false"
            childElements:
            - name: "awayMoneyline"
              datatype: "VARIANT"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "awayMoneyline"
              isArray: "false"
              include: "false"
            - name: "homeMoneyline"
              datatype: "VARIANT"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "homeMoneyline"
              isArray: "false"
              include: "false"
            - name: "overUnder"
              datatype: "VARIANT"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "overUnder"
              isArray: "false"
              include: "false"
            - name: "overUnderOpen"
              datatype: "VARIANT"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "overUnderOpen"
              isArray: "false"
              include: "false"
            - name: "spread"
              datatype: "VARIANT"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "spread"
              isArray: "false"
              include: "true"
            - name: "provider"
              datatype: "VARCHAR"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "provider"
              isArray: "false"
              include: "true"
            - name: "spreadOpen"
              datatype: "VARIANT"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "spreadOpen"
              isArray: "false"
              include: "false"
            - name: "formattedSpread"
              datatype: "VARCHAR"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "formattedSpread"
              isArray: "false"
              include: "true"
        - name: "season"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "season"
          isArray: "false"
          include: "false"
        - name: "seasonType"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "seasonType"
          isArray: "false"
          include: "false"
        - name: "week"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "week"
          isArray: "false"
          include: "false"
        - name: "startDate"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "startDate"
          isArray: "false"
          include: "false"
        - name: "id"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "id"
          isArray: "false"
          include: "false"
        outerJoin: "False"
        inputAlias: "i"
        arrayPrefix: "f"
    Rewrite Table 0:
      type: "rewrite-table"
      sources:
      - "Join 0"
      parameters:
        componentName: "Rewrite Table 0"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "cfb_upset"
    Filter 0:
      type: "filter"
      sources:
      - "Rank 0"
      parameters:
        componentName: "Filter 0"
        filterConditions:
        - - "rn"
          - "Is"
          - "Equal to"
          - "1"
        combineCondition: "AND"
    PlayerStats:
      type: "table-input"
      parameters:
        componentName: "PlayerStats"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "PlayerStats"
        columnNames:
        - "category"
        - "conference"
        - "playerid"
        - "stat"
        - "stattype"
        - "team"
        - "player"
        timeOffset: ""
    Upset Amount:
      type: "calculator"
      sources:
      - "Calculator 0"
      parameters:
        componentName: "Upset Amount"
        includeInputColumns: "Yes"
        calculations:
        - - "CASE WHEN trim(\"projectedWinner\",' ') <> trim(\"actualWinner\",' ')\
            \ THEN (\"spread\"+\"scoreDifference\") \nWHEN trim(\"projectedWinner\"\
            ,' ') = trim(\"actualWinner\",' ') THEN ABS(\"scoreDifference\"-\"spread\"\
            ) \nELSE 0 END "
          - "pointDifferential"
        - - "CASE WHEN trim(\"projectedWinner\",' ') <> trim(\"actualWinner\",' ')\
            \ THEN 'upset' \nELSE 'expected winner won' END"
          - "result"
    Join 0:
      type: "join"
      sources:
      - "Upset Amount"
      - "PlayerStats"
      parameters:
        componentName: "Join 0"
        mainTable: "Upset Amount"
        mainTableAlias: "games"
        joins:
        - - "PlayerStats"
          - "away_stats"
          - "Left"
        - - "PlayerStats"
          - "home_stats"
          - "Left"
        joinExpressions:
        - - "\"games\".\"awayTeam\" = \"away_stats\".\"team\"\nAND \"away_stats\"\
            .\"stattype\" = 'YDS' \nAND \"away_stats\".\"category\" = 'passing'\n\
            AND \"away_stats\".\"stat\" = (select max(\"stat\") from \"PC_MATILLION_DB\"\
            .\"PUBLIC\".\"PlayerStats\" AS \"s\" where \n\t\t\t\t\t\"s\".\"team\"\
            \ = \"away_stats\".\"team\" AND \"s\".\"stattype\" = 'YDS' AND \"s\".\"\
            category\" = 'passing')"
          - "games_Left_away_stats"
        - - "\"games\".\"homeTeam\" = \"home_stats\".\"team\"\nAND \"home_stats\"\
            .\"stattype\" = 'YDS' \nAND \"home_stats\".\"category\" = 'passing'\n\
            AND \"home_stats\".\"stat\" = (select max(\"stat\") from \"PC_MATILLION_DB\"\
            .\"PUBLIC\".\"PlayerStats\" AS \"s\" where \n\t\t\t\t\t\"s\".\"team\"\
            \ = \"home_stats\".\"team\" AND \"s\".\"stattype\" = 'YDS' AND \"s\".\"\
            category\" = 'passing')"
          - "games_Left_home_stats"
        columnMappings:
        - - "games.actualWinner"
          - "actualWinner"
        - - "games.projectedWinner"
          - "projectedWinner"
        - - "games.pointDifferential"
          - "pointDifferential"
        - - "games.result"
          - "result"
        - - "games.awayTeam"
          - "awayTeam"
        - - "games.awayScore"
          - "awayScore"
        - - "away_stats.player"
          - "awayTeamQB"
        - - "games.homeTeam"
          - "homeTeam"
        - - "games.homeScore"
          - "homeScore"
        - - "home_stats.player"
          - "homeTeamQB"
        - - "games.formattedSpread"
          - "formattedSpread"
design:
  components:
    BettingOdds:
      position:
        x: 243
        "y": 89
      tempMetlId: 71548
    Rank 0:
      position:
        x: 544
        "y": 96
      tempMetlId: 71550
    Calculator 0:
      position:
        x: 832
        "y": 96
      tempMetlId: 71552
    Extract Nested Data 0:
      position:
        x: 397
        "y": 96
      tempMetlId: 71553
    Rewrite Table 0:
      position:
        x: 1296
        "y": 96
      tempMetlId: 71554
    Filter 0:
      position:
        x: 688
        "y": 96
      tempMetlId: 71555
    PlayerStats:
      position:
        x: 1120
        "y": -16
      tempMetlId: 71556
    Upset Amount:
      position:
        x: 976
        "y": 96
      tempMetlId: 71557
    Join 0:
      position:
        x: 1113
        "y": 93
      tempMetlId: 71559
